ssz/README.md
Sorry, I should have caught this yesterday! 😅
=> Fixed one more ssz.py broken link

README.md
Just fixing a few typos, spellings (to American), and readability improvements.
=> Luke's review of Readme.md

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Add some simple PR and issue templates to guide contributors.
=> Add PR and issue templates

beacon_chain/utils/shuffling/src/lib.rs
#59 
- Fixes underflow
Ask for more info.
=> Fix underflow in shuffle with empty list

README.md
Sorry Shasper
NA
Change the main readme from Ethereum 2.0 -> Serenity
:)
=> Switch "Ethereum 2.0" to "Ethereum Serentity"

Cargo.toml, beacon_chain/chain/Cargo.toml, beacon_chain/chain/src/block_context.rs, beacon_chain/chain/src/block_processing.rs, beacon_chain/chain/src/genesis.rs, beacon_chain/chain/src/lib.rs, beacon_chain/chain/src/maps.rs, beacon_chain/chain/src/stores.rs, beacon_chain/chain/src/transition.rs, beacon_chain/chain/tests/main.rs, beacon_chain/naive_fork_choice/Cargo.toml, beacon_chain/naive_fork_choice/src/lib.rs, beacon_chain/state-transition/Cargo.toml, beacon_chain/state-transition/src/lib.rs, beacon_chain/types/src/active_state.rs, beacon_chain/types/src/crystallized_state.rs, beacon_chain/utils/ssz_helpers/src/ssz_beacon_block.rs, beacon_chain/validation/src/block_validation.rs, beacon_chain/validation/tests/block_validation/helpers.rs, beacon_chain/validation/tests/block_validation/tests.rs, lighthouse/db/src/disk_db.rs, lighthouse/db/src/memory_db.rs, lighthouse/db/src/stores/beacon_block_store.rs, lighthouse/db/src/traits.rs
NA
Add a very basic (incomplete) `BeaconChain` struct which should eventually serve as the main blockchain state machine.
This is not tested -- it will be able to be tested after some validator logic is introduced.
=> Implement core chain logic

.travis.yml
NA
Add `--all` scripts to travis.yml
Travis isn't actually running any tests because it is a workspace.
=> [WIP] Make travis run all tests

beacon_chain/utils/boolean-bitfield/src/lib.rs, beacon_chain/validation/src/attestation_validation.rs
Fixes #86 .
Updates implementation to follow the Python reference implementation.
=> Fix boolean bitfield serde bug

docs/onboarding.md
#93 Update onboarding docs
* Add more detailed insight into Lighthhouse ideology.
* Update Ethereum/Serenity background information/docs.
* Add basic coding conventions.
The README has detailed quite a bit of information regarding Serenity/Beacon-Chain so I tried to minimize the overlap here. 
There's also a few things I've missed so I would love to get any input! :smile:
=> [WIP] Update onboarding documentation

README.md
N/A
Added a few documentation changes mostly for Windows setup
N/A
=> Add windows notes to readme and fix some grammar errors

README.md, eth2/README.md
NA
- Update main readme
- Add readme to `eth2/`
NA
=> Readme updates

eth2/fork_choice/src/bitwise_lmd_ghost.rs, eth2/types/src/slot_height.rs
Updates bitwise ghost to u64 slot heights.
=> Convert bitwise ghost to use u64 block heights.

eth2/utils/ssz_derive/src/lib.rs
Resolves #272 
Fix algorithm to use merkle_hash for containers
=> Brought algorithm in TreeHash macro up to spec

docs/lighthouse.md
=> docs: Fix typo

docs/onboarding.md
=> docs: Fix typos

validator_client/src/config.rs, validator_client/src/main.rs
Resolves #252 - ChainSpec is fixed to Foundation
Make ChainSpec selectable via CLI Flag.
=> ChainSpec selectable via CLI flag

Cargo.toml, eth2/utils/merkle_proof/Cargo.toml, eth2/utils/merkle_proof/src/lib.rs
Required for #281 (namely deposit validation)
Add a function `verify_merkle_proof` which can be used to validate a Merkle proof
=> Implement library for verifying Merkle proofs

eth2/types/src/test_utils/testing_attester_slashing_builder.rs
NA
Reduces duplicate tree hashing. Improves benchmark setup times.
Does not touch production code.
=> Optimize TestingAttesterSlashingBuilder

eth2/fork_choice/src/lib.rs, eth2/fork_choice/src/optimized_lmd_ghost.rs, eth2/fork_choice/tests/tests.rs
Addressed #269 
Added a new optimized fork choice rule which is an improvement over slow LMD ghost. Changes the `choose_best_child` function to simply select the child with the highest votes in the children hashmap. Tested using test cases in `lmd_ghost_test_vectors.yaml`
=> [WIP] Add OptimizedLMDGhost fork choice rule and tests

eth2/fork_choice/tests/bitwise_lmd_ghost_test_vectors.yaml, eth2/fork_choice/tests/lmd_ghost_test_vectors.yaml
Addresses #247 
Adds additional tests for lmd_ghost and bitwise_lmd_ghost fork choice rules.
=> Adds additional tests for lmd ghost fork choice rules

eth2/utils/bls/Cargo.toml
NA
Updates to the latest BLS library version.
Implements a faster `Eq` method.
=> Update signature-scheme to v0.6.1

.editorconfig
Adds an editor config template for new contributors.
=> Add editorconfig template

beacon_node/eth2-libp2p/Cargo.toml, beacon_node/eth2-libp2p/src/config.rs, beacon_node/eth2-libp2p/src/rpc/protocol.rs, beacon_node/eth2-libp2p/src/service.rs, eth2/types/Cargo.toml
Updates master to lastest version of libp2p and gossipsub.
=> Libp2p patch

LICENSE
See Issue #326
Re-licensing Lighthouse to Apache 2.0
=> Update License to Apache 2.0

beacon_node/beacon_chain/test_harness/tests/chain.rs, eth2/fork_choice/tests/tests.rs, eth2/state_processing/tests/tests.rs
Resolves #348
Move some long-running tests to release only.
=> Move some long-running tests to release-only

eth2/utils/cached_tree_hash/src/btree_overlay.rs, eth2/utils/cached_tree_hash/src/lib.rs
NA
Marginally improves the docs for `cached_tree_hash`
NA
=> Small docs improvement

eth2/state_processing/src/per_block_processing/block_processing_builder.rs, eth2/state_processing/src/per_block_processing/tests.rs
Master build is failing
- Run `cargo fmt --all`
NA
=> Fix failing master build

beacon_node/eth2-libp2p/src/rpc/protocol.rs
#394
Fixes SSZ encoding of `RPCEvent`.
NA
=> Fix bug in RPC wire encoding

README.md
(minor change to readme)
Please list or describe the changes introduced by this PR.
Added Large File Storage step so EF tests pass
Please provide any additional information. For example, future considerations
or information useful for reviewers.
=> Added Large File Storage step to instructions

docs/installation.md
-
Added large file support step to install notes
-
=> Update installation notes to include git-lfs step.

docs/installation.md
Addresses #458.
Add `git submodule update` to installation docs.
N/A
=> Fix submodule init command in docs to also update

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/fork_choice.rs, beacon_node/beacon_chain/src/test_utils.rs, beacon_node/beacon_chain/tests/tests.rs, beacon_node/store/src/iter.rs, eth2/lmd_ghost/Cargo.toml, eth2/lmd_ghost/src/reduced_tree.rs, eth2/lmd_ghost/tests/test.rs
NA
Adds additional testing to `ReducedTree` LMD GHOST fork choice, finds and fixes bugs.
Bugs resulted in the reduced tree losing it's integrity (dangling pointers, multiple roots, etc).
=> Fork choice bug fixes

README.md
NA
- Remove gitter badge
- Add discord badge
=> Change gitter link to discord

eth2/state_processing/src/per_block_processing/is_valid_indexed_attestation.rs
=> Naughty Naughty Paul

CONTRIBUTING.md, README.md, book/src/SUMMARY.md, book/src/intro.md, book/src/lighthouse.md, book/src/onboarding.md, book/src/serenity.md
Fixes #533 
- Add back onboarding doc and lighthouse doc to book.
- Change gitter references to Discord
=> Add about and onboarding to book

beacon_node/beacon_chain/src/beacon_chain.rs
Closes #565 
Add log when trying to skip more than 3 blocks
=> Warn during long beacon state skips

eth2/utils/bls/src/keypair.rs
=> Derive `PartialEq` for Keypair

beacon_node/network/src/message_handler.rs, validator_client/src/attestation_producer/mod.rs, validator_client/src/block_producer/mod.rs, validator_client/src/duties/mod.rs
NA
Run `cargo fmt --all` on `master` to appease the CI.
=> Run cargo-fmt on master

beacon_node/eth2-libp2p/Cargo.toml
Found some pretty serious issues with discv5. 
This PR updates master to address these issues.
=> Apply discv5 fixes

eth2/utils/ssz_derive/src/lib.rs, eth2/utils/tree_hash_derive/src/lib.rs
Fixes #620 by making the result type explicit.
=> Fix custom derive macros

beacon_node/eth1/tests/test.rs
Closes #626 
Increase timeout duration
=> increase timeout duration

beacon_node/rest_api/src/validator.rs
Closes #631 
- Use RelativeEpoch without state loading if epoch is within RelativeEpoch range (previous, current or next) of the current state head.
=> Optimize validator duties API endpoint

beacon_node/rest_api/tests/test.rs
Closes #632 
Adding cfg! test for fake_crypto in `validator_block_post` test.
=> Add cfg! check for fake_crypto

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/errors.rs, beacon_node/rest_api/src/validator.rs, beacon_node/rest_api/tests/test.rs
NA
- Change functionality in `rest_api`.
- Time-based max skip-slots.
Very small bug-fix PR.
=> Address bugs

eth2/types/src/chain_spec.rs
That was created in the previous merge commit, as CI doesn't test merges :(
=> Remove duplication from bad merge

beacon_node/eth2-libp2p/src/rpc/codec/ssz.rs, beacon_node/eth2-libp2p/src/rpc/protocol.rs
Renames and consolidates RPC protocol names
=> Correct and consolidate RPC protocol names

beacon_node/rest_api/src/validator.rs, beacon_node/rest_api/tests/test.rs, validator_client/src/duties_service.rs
=> Allow multiple proposals per validator per epoch

beacon_node/store/src/hot_cold_store.rs
NA
Removes a couple of print statements introduced in #672
=> Remove a dbg! and println!

beacon_node/client/src/notifier.rs
NA
Stops the notifier from stopping during heavy syncing.
=> Add timeout when notifier waits for libp2p lock

book/src/become-a-validator.md
None
Fix two minor typos in the book
=> Fix two minor typos in book

book/src/installation.md
Closes #690 
Added a note about making sure that the user is running the latest version of the rust compiler.
=> Add note about rustup update

eth2/types/src/chain_spec.rs
Closes #704 
MAX_SEED_LOOKAHEAD is now part of the YamlConfig!
=> Add max_seed_lookahead to yamlconfig

lighthouse/environment/src/lib.rs, lighthouse/src/main.rs
Closes #638 
Add support for logging level when using the `--logfile` flag.
Tested it myself using different combination of flags, I believe it's working as intended. :D
=> Add logging level when using logfile

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/tests/tests.rs, eth2/operation_pool/src/lib.rs, eth2/operation_pool/src/persistence.rs
Closes #716 
Delete some codez.
=> Delete outdated deposits handling in operation pool

Dockerfile
NA
This should help to shrink the size of the docker image.
=> Clean cargo in dockerfile

book/src/become-a-validator.md
Adds a banner to tell peeps our testnet is down.
=> Add banner for testnet being down

beacon_node/src/config.rs
Closes #724 
- Fixed a bug where --datadir would not find the directory
- Updated corresponding error message
- Fixed clippy lints in `beacon_node/src/config.rs`
=> Fix --datadir cli option

book/src/js/deposit.js
Resolves #763
Updates the deposit contract to point to the `testnet3` contract.
=> Update deposit contract in docs

beacon_node/network/src/message_processor.rs
Upgrades a trace to debug for debugging sync issues on boot nodes.
=> Upgrade Sync Logging

beacon_node/beacon_chain/src/beacon_chain.rs, lighthouse/Cargo.toml
NA
Bump version tags for v0.1.1
=> Bump version tags

.dockerignore, Dockerfile
NA
Increase rust version for docker builder, ignore some more files so we don't need as large of a build context.
=> Bump docker rust version

eth2/operation_pool/src/lib.rs
Fixes #805 
- Fix logic error as stated in #805
=> Fix logic error in operation pool

book/src/become-a-validator.md
=> Add testnet down notice

Cargo.lock, eth2/utils/bls/Cargo.toml, eth2/utils/eth2_interop_keypairs/Cargo.toml
N/a this is a general optimisation.
Switch the branch of [sigp/milagro_bls](https://github.com/sigp/milagro_bls/pull/13) to one with new optimisations.
This should be updated in the future to refer to point to a specific tag rather than to a branch when the above PR is merged.
=> Faster BLS Verification

Cargo.lock, beacon_node/eth2-libp2p/Cargo.toml
Updates an issue is discv5 where queries would never complete.
=> Discv5 query search fix

Cargo.lock, beacon_node/beacon_chain/Cargo.toml, beacon_node/beacon_chain/src/eth1_chain.rs, beacon_node/beacon_chain/src/metrics.rs, eth2/types/src/chain_spec.rs, tests/beacon_chain_sim/src/main.rs
N/A
Update eth1 voting scheme to purely timestamp based as in v0.10.1.
=> Update to latest eth1 voting scheme

Dockerfile
=> Bump Rust version for dockerfile to 1.41

book/src/SUMMARY.md, book/src/http.md, book/src/http_advanced.md, book/src/http_beacon.md, book/src/http_network.md, book/src/http_spec.md, book/src/http_validator.md
N/A
Add docs for undocumented api endpoints.
.
=> Update docs for api endpoints

beacon_node/eth2-libp2p/src/rpc/handler.rs
It is possible to simultaneously error on RPC negotiations before a handler `poll()` gets called. This PR queues the errors before reporting back the user the failed RPC negotiation upgrade.
=> Handle simultaneous RPC negotiation errors

Cargo.lock, beacon_node/eth2-libp2p/tests/common/mod.rs, beacon_node/network/Cargo.toml, beacon_node/network/src/service/tests.rs
N/A
Fixes the dht persistence tests and libp2p tests to work with the network crate changes.
=> Fix dht persistence test

account_manager/src/lib.rs, eth2/types/src/chain_spec.rs
NA
- Ensures that the YAML config applies it's genesis fork to the chain spec
- Ensure the account manager uses the spec it gets from the testnet dir.
=> Ensure deposits are generated with correct fork

book/src/js/deposit.js
NA
Updates the deposit contract address in the Metamask JavaScript.
=> Update book deposit contract address

tests/eth1_test_rig/src/ganache.rs
=> Correct typo

beacon_node/client/src/builder.rs
The component that required in the line this PR fixed is RuntimeContext not Logger. 😃
=> Fix incorrect error message in ClientBuilder

beacon_node/beacon_chain/tests/attestation_production.rs
Merging #861 caused a compile issue on master. This fixes it.
=> Fix compile issue on master

book/src/http_validator.md
=> Validator API book correction

beacon_node/beacon_chain/tests/attestation_tests.rs, beacon_node/beacon_chain/tests/store_tests.rs, beacon_node/beacon_chain/tests/tests.rs, beacon_node/network/src/persisted_dht.rs, beacon_node/network/src/service.rs, beacon_node/network/src/service/tests.rs, eth2/operation_pool/src/lib.rs
Corrects release tests to pass CI
=> Test corrections

eth2/utils/eth2_testnet_config/build.rs
This PR fixes https://github.com/sigp/lighthouse/issues/930 :octocat:
=> Eth2TestnetConfig: Fix incomplete build

beacon_node/network/src/attestation_service/mod.rs
This fixes an underflow in the attester service logic.
=> Timing correction in the attester service

Cargo.lock, beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/block_verification.rs, beacon_node/beacon_chain/src/errors.rs, beacon_node/network/src/sync/range_sync/batch_processing.rs, eth2/utils/slot_clock/src/lib.rs, eth2/utils/slot_clock/src/manual_slot_clock.rs, eth2/utils/slot_clock/src/system_time_slot_clock.rs
Updates block processing logic for gossip for the v0.2.0 branch
=> Re-merge updated block processing to v0.2.0

beacon_node/network/src/attestation_service/mod.rs
Sends a discovery request for persistent subnets.
=> Send discovery request for persistent subnets

book/src/SUMMARY.md, book/src/become-a-validator-docker.md, book/src/become-a-validator-source.md, book/src/faq.md
NA
Adds an FAQ section with an answer to "Why does it take so long for a validator to be activated". We've had this question a lot, so it'll be nice to point people here.
=> Add FAQ section to the book

eth2/state_processing/src/per_block_processing.rs, eth2/types/src/beacon_state.rs, eth2/types/src/beacon_state/tests.rs
=> Fix Eth1 data underflow

.github/workflows/test-suite.yml, Makefile, eth2/state_processing/benches/benches.rs, eth2/types/benches/benches.rs, eth2/types/src/beacon_state/tests.rs, eth2/utils/tree_hash/benches/benches.rs
=> Update benchmarks, add to CI

beacon_node/eth2-libp2p/src/behaviour.rs, beacon_node/eth2-libp2p/src/peer_manager/client.rs, beacon_node/eth2-libp2p/src/peer_manager/mod.rs, beacon_node/eth2-libp2p/src/peer_manager/peer_info.rs
Integrates identify information into the peer management database.
=> Integrate identify into peer manager

lcli/Cargo.toml, tests/eth1_test_rig/src/lib.rs
=> Fix eth1_test_rig

beacon_node/eth2-libp2p/tests/common/mod.rs, beacon_node/eth2-libp2p/tests/gossipsub_tests.rs, beacon_node/network/src/router/processor.rs, beacon_node/rest_api/src/node.rs, beacon_node/src/config.rs
Updates status message to send the correct fork digest
=> Correct status fork digest

Cargo.lock, account_manager/src/cli.rs, beacon_node/client/src/notifier.rs, beacon_node/eth2-libp2p/Cargo.toml, beacon_node/eth2-libp2p/src/config.rs, beacon_node/eth2-libp2p/src/discovery/mod.rs, beacon_node/eth2-libp2p/src/peer_manager/peerdb.rs, beacon_node/eth2-libp2p/src/rpc/handler.rs, beacon_node/network/src/sync/manager.rs, beacon_node/src/cli.rs
- Discv5 bug fixes
- Discv5 query timesouts
- Allow compilation in debug
- Correct bug in peer discovery
- Connect notifier to sync manager log and modify log outputs
=> Various corrections pre-testnet

eth2/utils/remote_beacon_node/src/lib.rs, tests/simulator/src/sync_sim.rs
Continuation of #943 
- include node/syncing in `remote_beacon_node`
- use this in the sync sim
=> Sync sim mini update

Cargo.lock, beacon_node/eth2-libp2p/src/discovery/mod.rs, beacon_node/eth2-libp2p/src/peer_manager/mod.rs, beacon_node/eth2-libp2p/src/peer_manager/peer_info.rs, beacon_node/eth2-libp2p/src/peer_manager/peerdb.rs, beacon_node/eth2-libp2p/src/service.rs, beacon_node/eth2-libp2p/src/types/globals.rs, beacon_node/network/src/router/mod.rs, beacon_node/network/src/router/processor.rs, beacon_node/network/src/service.rs, beacon_node/network/src/sync/manager.rs
- Bug fix for nodes falling of out sync indefinitely (noticed on testnet)
- Bug fix for peers randomly disconnecting during initial handshakes in the simulator and on testnets
- Improved log handling
=> Sync corrections

beacon_node/rest_api/src/helpers.rs, beacon_node/rest_api/src/validator.rs, eth2/types/src/attestation.rs, eth2/types/src/beacon_state.rs, eth2/types/src/selection_proof.rs, validator_client/src/attestation_service.rs
NA
Addresses the some clippy lints detected by @michaelsproul's fancy new linter.
=> Address clippy arith lints in v0.2.0

beacon_node/beacon_chain/src/beacon_chain.rs
NA
When processing a chain segement, skip any block that is from a finalized slot.
=> Skip an already finalized block in a segment

beacon_node/eth2-libp2p/src/peer_manager/peer_sync_status.rs, beacon_node/network/src/router/processor.rs, beacon_node/network/src/sync/manager.rs, beacon_node/network/src/sync/peer_sync_info.rs, beacon_node/network/src/sync/range_sync/chain.rs, beacon_node/network/src/sync/range_sync/mod.rs, beacon_node/network/src/sync/range_sync/range.rs, beacon_node/network/src/sync/range_sync/sync_type.rs
A variety of small issues are addressed in this PR:
- Correction and code improvements for identifying peer's on a separate chain for a finalized chain sync.
- Handling spontaneous STATUS messages during long-range syncs
- Improved logging
=> Sync and multi-client updates

Cargo.lock, beacon_node/eth2-libp2p/Cargo.toml, beacon_node/eth2-libp2p/src/behaviour.rs, beacon_node/eth2-libp2p/src/config.rs, beacon_node/eth2-libp2p/src/peer_manager/mod.rs, beacon_node/network/src/attestation_service/mod.rs, beacon_node/network/src/sync/manager.rs
- Resolves incorrect PING RPC request
- Adds attestation subnet verification
- Improves PING and STATUS timing handling
- Adds discv5 bug fixes
=> Testnet corrections

eth2/operation_pool/src/lib.rs, eth2/state_processing/src/per_block_processing.rs, eth2/state_processing/src/per_block_processing/tests.rs
Closes #1065
Remove parallelism from proposer slashing verification. Other parallelism is left in for now. Tests added for both block processing and the op pool.
It turns out the op pool was already OK wrt to the bug. The map from proposer index to `ProposerSlashing` ensures we only keep (and return) at most only slashing per proposer.
=> Fix duplicate proposer slashing bug

Cargo.lock, beacon_node/Cargo.toml, beacon_node/src/config.rs, eth2/utils/clap_utils/src/lib.rs
- Resolves #1061
Adds more detail to error when testnet directory is invalid.
=> Add more detail to bad hardcoded dir error

beacon_node/eth2-libp2p/src/peer_manager/mod.rs
Panic occur due to unexpected behaviour in tokio's DelayQueue. 
This adds a temporary workaround to correct the behaviour of the delayqueue until we implement stable futures and latest tokio (which doesn't have this issue). 
This hopefully addresses #1067
=> Correctly notify delay queues

beacon_node/client/src/builder.rs, beacon_node/eth1/src/service.rs, beacon_node/src/config.rs, beacon_node/src/lib.rs
- Resolves #1074
- Fixes a bug raised by @mpetrunic where `ETH1_FOLLOW_DISTANCE` was not respected by the beacon node.
- Adds more `info` and `debug` logs for eth1 following actions.
- Converts some single-variant enums into structs (code-quality)
=> Follow distance fix

beacon_node/eth2-libp2p/src/discovery/enr_ext.rs
Fixes conversion function from peer id to node id and adds tests
=> Fix peer_id_to_node_id

account_manager/Cargo.toml, account_manager/src/deposits.rs, account_manager/src/lib.rs, validator_client/src/validator_directory.rs
Port account manager to stable futures. 
@AgeManning  I think that this crate could be tested standalone. So still keeping this as WIP till I complete testing.
=> Port account_manager to stable futures

beacon_node/network/src/service/tests.rs, beacon_node/websocket_server/src/lib.rs
- Fixes network `persisted_dht` test (in a bit of a hacky way since we no longer have `block_on_all` in  `tokio 0.2` )
- Fixes all the `rest_api` tests by spawning the websocket handler in an OS thread instead of a tokio threadpool. Earlier, the single threaded runtime in the `rest_api` tests were getting hung up on the websocket handler and not progressing to shutdown everything else after the tests completed.
=> Test fixes

lcli/src/deploy_deposit_contract.rs, lcli/src/eth1_genesis.rs, lcli/src/main.rs, lcli/src/refund_deposit_contract.rs
Remove `tokio::main` runtime from lcli.
=> Fix multiple runtimes in lcli

beacon_node/network/src/router/processor.rs
Lighthouse could send duplicate blocks to a BlocksByRequest with a step parameter that is not 1 in the presence of skip slots.
This corrects this logic to align with the specification.
=> Corrects handling of BlocksByRange step parameter around skip slots

beacon_node/beacon_chain/src/builder.rs
Fixed error messages that doesn't match the function name.
I can not find an equivalent of `__function__` in Rust. 🤔
=> Fix error messages

eth2/types/src/beacon_state/exit_cache.rs
=> Fix CI - fmt correction

beacon_node/eth2-libp2p/src/peer_manager/mod.rs, beacon_node/eth2-libp2p/src/service.rs, beacon_node/eth2-libp2p/src/types/globals.rs, beacon_node/network/src/attestation_service/mod.rs, beacon_node/network/src/router/mod.rs, beacon_node/network/src/router/processor.rs
Adds a "client" to a number of warning logs to help identify clients with RPC errors/warnings
=> Client identification

book/src/become-a-validator.md
NA
See description and changes.
=> Update docs to indicate that Schelsi is down

consensus/state_processing/src/per_epoch_processing/registry_updates.rs
=> Avoid implicit validator status assumption

Cargo.lock, consensus/types/Cargo.toml, validator_client/slashing_protection/Cargo.toml
=> Update rusqlite to safer v0.23

Dockerfile
N/A
Upgrade rust version in Dockerfile to latest stable.
=> Upgrade docker rust version

account_manager/src/common.rs, account_manager/src/validator/create.rs, account_manager/src/wallet/create.rs
=> Strip new lines in validator create

consensus/ssz_derive/src/lib.rs
NA
Fixes this clippy lint:
```
warning: unsequenced read of a variable
--> consensus/types/src/validator.rs:13:67
|
13 | #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Encode, Decode, TestRandom, TreeHash)]
|                                                                   ^^^^^^
|
note: whether read occurs before this write depends on evaluation order
```
=> Fix eval-order clippy lint

beacon_node/eth2-libp2p/Cargo.toml
fix `tokio` compilation issue using beaconfuzz/eth2fuzz
=> fix compilation issue using beaconfuzz/eth2fuzz

beacon_node/eth2-libp2p/src/rpc/handler.rs, beacon_node/eth2-libp2p/src/rpc/mod.rs
The keep alive logic had some inconsistencies, so have a function that centralizes this logic. Also update where the keep alive is updated
=> Update the RPC handler's keep alive logic

.github/workflows/test-suite.yml, Cargo.lock, beacon_node/rest_api/src/metrics.rs, beacon_node/rest_api/tests/test.rs, common/rest_types/Cargo.toml, common/rest_types/src/node.rs
Builds on MacOS are failing after #1197 was merged into master.
The last known good commit for MacOS is: https://github.com/sigp/lighthouse/commit/58a9f979e01a3d6c79038f5e9a3bafb6504fb505
- Adds release tests for MacOS to CI
=> Ensure new health endpoint builds on MacOS

book/src/become-a-validator-docker.md, common/validator_dir/src/manager.rs
NA
Updates the docs as per the changes in https://github.com/sigp/lighthouse-docker/pull/8
=> Update docs to suit sigp/docker-compose updates

beacon_node/beacon_chain/src/attestation_verification.rs, beacon_node/beacon_chain/tests/attestation_verification.rs
Part of #1182
Building on #1228, updates the attestation gossip verification rules for v0.12.0
~~Blocked on #1228~~
=> Attestation gossip verification v0.12

book/src/SUMMARY.md, book/src/installation.md, book/src/pi.md
NA
- Add a simple installation guide for Raspberry Pi 4.
- List `cmake` as a dep
NA
=> Add raspberry pi docs

README.md
- Remove beaconcha.in link.
- Update roadmap
=> Update main REAMDE

beacon_node/beacon_chain/src/beacon_chain.rs
NA
Addresses an informational in ToB report.
No functional changes, only code quality.
=> Replace unreachable expect with tidier solution

beacon_node/eth2_libp2p/src/rpc/handler.rs
=> fix wrong draining of queued requests on handler shutdown

validator_client/src/lib.rs, validator_client/src/validator_store.rs
NA
Decrypts validator keystores before connecting to the BN.
This fixes an issue I observed when the VC:
- is started prior to genesis
- has lots of validators (e.g., 1024)
In this scenario, the VC would wait until the genesis instant before it decrypted the validator keys. Since this took a couple/few minutes, we missed the first slots of the chain.
=> Decrypt keys earlier in VC lifecycle

common/eth2_testnet_config/build.rs
NA
Changes the commit for the testnet dir download so it includes @q9f's boot-enr
=> Add Altona bootnodes

common/eth2_testnet_config/.gitignore, common/eth2_testnet_config/build.rs, common/eth2_testnet_config/src/lib.rs
NA
- Update to latest genesis time (after correction).
- Add genesis state
NA
=> Update to latest Altona genesis time

book/src/SUMMARY.md, book/src/become-a-validator.md
NA
Replace references to Witti with Altona.
=> Update docs for Altona

beacon_node/eth1/src/service.rs
=> Fixed 1 line bug

common/eth2_testnet_config/build.rs, common/eth2_testnet_config/src/lib.rs
NA
Adds the boot enr from here: https://github.com/eth2-clients/eth2-testnets/blob/master/shared/altona/bootstrap_nodes.txt
NA
=> Add more Altona boot ENR

Cargo.lock, beacon_node/beacon_chain/Cargo.toml, beacon_node/beacon_chain/tests/store_tests.rs, beacon_node/store/src/errors.rs, beacon_node/store/src/hot_cold_store.rs, beacon_node/store/src/leveldb_store.rs, beacon_node/store/src/lib.rs, beacon_node/store/src/memory_store.rs
Follow up to https://github.com/sigp/lighthouse/pull/1285#discussion_r445471441
Should be the last PR related to atomicity (https://github.com/sigp/lighthouse/issues/692).
=> Harden the freezing procedure against failures

book/src/become-a-validator-source.md, book/src/faq.md
=> Correct book links

beacon_node/eth2_libp2p/src/peer_manager/mod.rs
#1291 
Turn off periodic status updates during syncing.
=> Do not send regular status updates during syncing

beacon_node/client/src/config.rs, beacon_node/src/config.rs, beacon_node/src/lib.rs, common/clap_utils/src/lib.rs, common/eth2_testnet_config/build.rs, common/eth2_testnet_config/src/lib.rs, lighthouse/environment/tests/environment_builder.rs, lighthouse/src/main.rs
=> Add testnet flags

beacon_node/eth2_libp2p/src/behaviour/mod.rs, beacon_node/network/src/service.rs
Fixes two bugs in the networking stack.
=> Networking bug fixes

Cargo.lock, account_manager/Cargo.toml, beacon_node/Cargo.toml, boot_node/Cargo.toml, common/lighthouse_version/src/lib.rs, lcli/Cargo.toml, lighthouse/Cargo.toml, validator_client/Cargo.toml
N/A
- Bump to `v0.2.13`
- Run `cargo update`
N/A
=> Version bump to v0.2.13

validator_client/src/lib.rs
Fixes an issue where VCs would wait until the genesis instant to fail on a mismatched spec configuration.
NA
=> Check VC/BN spec compat before waiting for genesis
