lighthouse/db/src/disk_db.rs, lighthouse/db/src/memory_db.rs, lighthouse/db/src/traits.rs
N/A
Add a `delete` method to `ClientDB` and therefore `MemoryDB` and `DiskDB`.
Rather small change. There are some formatting changes introduced by `rustfmt`.
@g-r-a-n-t this is the change I was mentioning on Gitter :)
=> Add delete method to ClientDB

beacon_chain/utils/vec_shuffle/src/lib.rs
Unnecessary saturating_sub in shuffler #59
=> removed unnecessary call to saturated_sub() in vec_shuffle

beacon_chain/types/src/candidate_pow_receipt_root_record.rs, beacon_chain/types/src/lib.rs, beacon_chain/types/src/shard_reassignment_record.rs, beacon_chain/types/src/state.rs
#73
This PR introduces the following types:
- `BeaconState`
- `ShardReassignmentRecord`
- `CandidatePoWReceiptRootRecord`
It does _not_ remove the existing `CrystallizedState` and `ActiveState` objects. These can be removed once the rest of the code base has been updated to use `BeaconState`. 
Rust doesn't have a built-in u24, so u32 is used in its place. This is consistent with the rest of the code base.
=> Add new `State` type and dependant types

beacon_chain/types/src/active_state.rs, beacon_chain/types/src/attestation.rs, beacon_chain/types/src/beacon_block.rs, beacon_chain/types/src/lib.rs, beacon_chain/utils/ssz_helpers/src/attestation_ssz_splitter.rs, beacon_chain/utils/ssz_helpers/src/ssz_beacon_block.rs, lighthouse/db/src/stores/beacon_block_store.rs
Addresses #82
Rename `AttestationRecord` -> `Attestation` globally.
Simple change.
=> Rename `AttestationRecord` -> `Attestation`

beacon_chain/types/src/validator_record.rs, beacon_chain/utils/active-validators/src/lib.rs, beacon_chain/validator_change/src/lib.rs, beacon_chain/validator_induction/src/inductor.rs
None
Use stronger typing for the `ValidatorStatus`.
Idea is to convert to opaque rust types as quickly as possible (wrt IO on the edges of the node). The general idea is that we won't accidentally be comparing some arbitrary bytes in the hope that we are correctly identifying validators.
=> Validator status typing

beacon_chain/types/src/attestation.rs, beacon_chain/utils/bls/Cargo.toml, beacon_chain/utils/bls/src/aggregate_signature.rs, beacon_chain/utils/bls/src/lib.rs, beacon_chain/utils/bls/src/signature.rs
None
Wrap the `Signature` and `AggregateSignature` BLS structs in a newtype struct. This provides the following:
- Simpler, cleaner SSZ serialization.
- Ability to swap out BLS libraries with more ease.
- Finer control over which crypto functions are made available to the rest of the program.
I considered using a `Deref` pattern but [this post](https://stackoverflow.com/a/45086999) put me off that method. I think cryptography is a good place to have absolute control over the methods that are available on a struct. This allows lighthouse to guide the usage of the underlying crypto by making "good" methods available and "bad" methods hidden.
It would be consistent to wrap all the BLS structs in newtypes. I leave this for a later time because:
1. I'd like feedback on the concept before going …
=> Wrap Signature and AggregateSignature in a newtype 

beacon_chain/attestation_validation/src/signature.rs, beacon_chain/chain/src/maps.rs, beacon_chain/types/src/beacon_state.rs, beacon_chain/types/src/candidate_pow_receipt_root_record.rs, beacon_chain/types/src/common/maps.rs, beacon_chain/types/src/common/mod.rs, beacon_chain/types/src/crosslink_record.rs, beacon_chain/types/src/deposit_input.rs, beacon_chain/types/src/fork_data.rs, beacon_chain/types/src/lib.rs, beacon_chain/types/src/pending_attestation_record.rs, beacon_chain/types/src/shard_committee.rs, beacon_chain/types/src/shard_reassignment_record.rs, beacon_chain/types/src/test_utils/address.rs, beacon_chain/types/src/test_utils/mod.rs, beacon_chain/types/src/validator_record.rs, beacon_chain/types/src/validator_registration.rs, beacon_chain/utils/bls/src/keypair.rs, beacon_chain/utils/bls/src/lib.rs, beacon_chain/utils/bls/src/public_key.rs, beacon_chain/utils/bls/src/secret_key.rs, beacon_chain/utils/bls/src/signature.rs, beacon_chain/utils/ssz/src/decode.rs, beacon_chain/utils/ssz/src/impl_decode.rs, beacon_chain/utils/ssz/src/impl_encode.rs, beacon_chain/validator_change/Cargo.toml, beacon_chain/validator_change/src/lib.rs, beacon_chain/validator_induction/src/inductor.rs, beacon_chain/validator_shuffling/src/shuffle.rs, lighthouse/db/src/stores/validator_store.rs
None.
Implement SSZ enc/decoding for `BeaconState` (and therefore all dependent structs) 
I didn't _really_ want to do this before the spec solidifies, but some work I'm doing requires that a `BeaconState` can stored in and retrieved from the DB.
=> Impl SSZ enc/dec for BeaconState

beacon_chain/utils/vec_shuffle/src/lib.rs, beacon_chain/utils/vec_shuffle/src/specs/shuffle_test_vectors.yaml
Closes #121.
I asked on `ethereum/sharding` and Mamy recommended
https://github.com/status-im/eth2-testgen/, so I just grabbed the yaml file from [here](https://github.com/status-im/eth2-testgen/blob/master/test_vectors/test_vector_shuffling.yml)
The file is CC0-licensed. I believe this is blocked by #109  before I even know how to hook this up to the unit test.
=> vec_shuffle: Add a keccak testsuite

.travis.yml, beacon_chain/attestation_validation/src/lib.rs, beacon_chain/genesis/src/lib.rs, beacon_chain/types/src/test_utils/mod.rs, beacon_chain/types/src/validator_record.rs, beacon_chain/utils/bls/src/lib.rs, beacon_chain/validator_induction/src/inductor.rs, beacon_chain/validator_induction/src/lib.rs, lighthouse/beacon_chain/tests/chain_test.rs, lighthouse/db/src/disk_db.rs, lighthouse/db/src/stores/beacon_state_store.rs, lighthouse/main.rs
Closes #143.
Adds `cargo fmt` to the CI process so that any commit that returns a non-empty diff will fail the pipeline.
=> Add rustfmt to travis

eth2/utils/bls/Cargo.toml
Partially address #91
This change is mentioned [here](https://github.com/sigp/signature-schemes/pull/2#issue-246077474). 
It would be helpful in this case and probably in the future to cut version branches off of master in the [signature-schemes](https://github.com/sigp/signature-schemes) repository whenever breaking changes are introduced. This way we can more easily coordinate updates to the BLS library spec.
If this gets merged, I can update the version in this [PR](https://github.com/sigp/signature-schemes/pull/2) to `0.2.0`, then make use of the `domain` parameter in a PR to lighthouse by changing the branch back to `master`.
This is the best solution I can think of at the moment to avoid breaking everyone's builds, but it could be more ideal, since this approach would always require …
=> added version to signature-schemes dependency

eth2/utils/ssz/src/tree_hash.rs
N/a
Modify when the chunk size is updated such that after the first round of merklizing the chunk size will be set to hashsize (and not before).
=> Merkle hashing chunk size fix

protos/build.rs
protos build fails on Windows due to incorrect directory separator character #165
Modified protos build file to use system line separator constant.
n/a
=> Fix hardcoded string to use system constant for directory separator

eth2/state_processing/Cargo.toml, eth2/state_processing/benches/benches.rs, eth2/state_processing/src/epoch_processable.rs, eth2/state_processing/src/epoch_processable/tests.rs, eth2/types/src/beacon_state.rs, eth2/types/src/beacon_state/builder.rs, eth2/types/src/beacon_state/tests.rs
NA
Adds benchmarking and a test for epoch processing. This PR is focused around creating a framework for testing, instead of introducing a lot of tests.
Detailed changes:
- Exposes the `BeaconStateBuilder` which was previously "hidden" in a test mod.
- Adds functionality for `BeaconStateBuilder` spawn a `BeaconBlock` immediately prior to an epoch transition with a full set of attestations.
- Fixes a bug with shuffling
- Adds a benchmark for epoch processing.
- Adds a test for epoch processing.
The `BeaconStateBuilder` is in the `beacon_state/builder.rs` file. This is not really 100% consistent but it seems succinct -- I'm indifferent about it. Happy to move it to `beacon_state_builder.rs` if that's preferred :)
=> Add benching and test for epoch processing

eth2/utils/fisher_yates_shuffle/Cargo.toml, eth2/utils/fisher_yates_shuffle/benches/benches.rs, eth2/utils/swap_or_not_shuffle/Cargo.toml, eth2/utils/swap_or_not_shuffle/benches/benches.rs
NA
- Adds benchmarks to `swap_or_not_shuffle`
- Adds benchmakrs to `fisher_yates_shuffle`
Times for shuffling a list of 16,384 items:
- swap or not: **2.1307 s**
- fisher yates: **1.0636 ms**
=> Add benchmarks to shuffling crates

beacon_node/beacon_chain/test_harness/Cargo.toml, beacon_node/beacon_chain/test_harness/benches/state_transition.rs, eth2/state_processing/benches/benches.rs, eth2/state_processing/src/epoch_processable/tests.rs, eth2/types/src/beacon_state.rs, eth2/types/src/beacon_state/builder.rs, eth2/types/src/beacon_state/tests.rs
NA
- Changes `BeaconState::per_epoch_processing(..)` to use 16k validators instead of 8.
- Adds the `BeaconStateBuilder::build_fast()` method to allow generating a `BeaconState` without generating keypairs and proof-of-possessions for each validator. This reduces the setup time for benchmarks by orders of magnitude.
Bench results:
```
epoch processing/pre-built caches
time:   [2.0584 s 2.0917 s 2.1076 s]
epoch processing/without pre-built caches
time:   [8.4381 s 8.4747 s 8.5258 s]
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) low severe
```
=> Move epoch benches to 16k validators

eth2/state_processing/src/epoch_processable.rs, eth2/state_processing/src/slot_processable.rs
NA
- Don't build the next cache at all.
- Call `advance_caches()` in per-slot processing.
Very small change. Building the cache inside the epoch is unnecessary and it slowed our benches down massively.
=> Remove cache operations from epoch processing

eth2/fork_choice/src/bitwise_lmd_ghost.rs, eth2/fork_choice/tests/bitwise_lmd_ghost_test_vectors.yaml
Correct inconsistency in choosing equally weighted children using the `get_clear_winner` optimisation, present in Vitalik's optimisation implementation (pointed out by @pawanjay176).
=> Correct bitwise fork-choice rule.

eth2/fork_choice/Cargo.toml, eth2/fork_choice/src/bitwise_lmd_ghost.rs
Remove floating point logarithms from the implementation of `log_int` so that it always computes the correct result.
The `test_power_of_2_below` test was failing on my machine, and I was super confused because I could see it was succeeding on CI. The assert `x <= std::f32::MAX as u32` was failing, and I eventually tracked this down as [undefined behaviour](https://doc.rust-lang.org/reference/expressions/operator-expr.html#semantics) (because the largest `f32` value doesn't fit in a `u32`). Removing the assert made the test pass, but then that got me thinking about whether there was a different assert I should add in its place...
In the end, I found that there were some inputs (close to powers of 2), for which the function would compute the incorrect result because of float rounding. …
=> Fix log_int implementation, removing floats

beacon_node/db/src/stores/beacon_block_store.rs, beacon_node/db/src/stores/macros.rs, beacon_node/db/src/stores/pow_chain_store.rs, eth2/fork_choice/src/bitwise_lmd_ghost.rs, eth2/state_processing/src/block_processable.rs, eth2/state_processing/src/epoch_processable.rs, eth2/types/Cargo.toml, eth2/types/src/attestation.rs, eth2/types/src/attestation_data.rs, eth2/types/src/attester_slashing/builder.rs, eth2/types/src/beacon_block.rs, eth2/types/src/beacon_state.rs, eth2/types/src/beacon_state/builder.rs, eth2/types/src/proposer_slashing/builder.rs, eth2/types/src/test_utils/address.rs, eth2/types/src/test_utils/hash256.rs, eth2/utils/ssz/Cargo.toml, eth2/utils/ssz/src/impl_decode.rs, eth2/utils/ssz/src/impl_encode.rs
Update to ethereum-types 0.5.0 #216
* Update `ethereum-types` to 0.5(.2)
* Use `from_slice` to convert byte slices to `Hash256`, as `Hash256::from` for slices has been removed
* Add explicit `as_bytes` conversions for `Hash256` to `&[u8]`. Previously not required due to a now-removed `Deref` impl
* Use `int_to_bytes32` in `generate_seed` to avoid confusion ([spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#generate_seed))
* Replace the arbitrary strings used for the epoch seeds in `teleport_to_end_of_epoch` with arbitrary byte arrays
* Add a `Hash256::from_short_slice` mixin to ease compatibility with existing tests that use slices of length less than 32
I'd like feedback on the last two points in particular, which feel a little bit suspect – …
=> Update ethereum-types to 0.5

beacon_node/db/src/stores/beacon_block_store.rs, eth2/fork_choice/tests/tests.rs, eth2/types/src/test_utils/testing_beacon_state_builder.rs
NA
- Add method for creating a testing beacon state where all validators use the same KP.
- Implement method in fork choice tests.
- Ignore long-running db test 
NA
=> Add TestingBeaconStateBuilder fn for cloned keypairs

eth2/types/src/attestation.rs, eth2/types/src/attestation_data.rs, eth2/types/src/attestation_data_and_custody_bit.rs, eth2/types/src/attester_slashing.rs, eth2/types/src/beacon_block.rs, eth2/types/src/beacon_block_body.rs, eth2/types/src/beacon_state/tests.rs, eth2/types/src/crosslink.rs, eth2/types/src/deposit.rs, eth2/types/src/deposit_data.rs, eth2/types/src/deposit_input.rs, eth2/types/src/eth1_data.rs, eth2/types/src/eth1_data_vote.rs, eth2/types/src/fork.rs, eth2/types/src/lib.rs, eth2/types/src/pending_attestation.rs, eth2/types/src/proposal.rs, eth2/types/src/proposer_slashing.rs, eth2/types/src/shard_reassignment_record.rs, eth2/types/src/slashable_attestation.rs, eth2/types/src/slot_epoch.rs, eth2/types/src/slot_epoch_macros.rs, eth2/types/src/slot_height.rs, eth2/types/src/test_utils/mod.rs, eth2/types/src/transfer.rs, eth2/types/src/validator.rs, eth2/types/src/voluntary_exit.rs
NA
As per #292, re-re-applies the changes that dedup SSZ tests.
I'm going to merge this because @michaelsproul made the changes and I've already reviewed them.
=> Re-re-apply removal of duplicated ssz_tests

eth2/utils/bls/src/signature.rs
#320 
Add `is_empty` to `bls::Siganture` struct.
Account for `is_empty` in verification and as/from bytes
I have chosen to allow aggregation of empty signatures as follows as this flows best:
```
AggregateSiganture(sig1, empty_signature) == AggregateSignature(sig1)
```
It may be more appropriate to instead to either return a `Result<(), AggregationError>` for Signature aggregation.
Thoughts?
=> Empty signature

.travis.yml, Jenkinsfile, eth2/utils/bls/src/fake_aggregate_signature.rs, eth2/utils/bls/src/fake_signature.rs, eth2/utils/bls/src/lib.rs
NA
Adds a `FakeSignature` and `FakeAggregateSignature` signature that replace `Signature` and `AggregateSignature` when compiling for debug.
The `Fake...` versions:
- Initialize to all zero bytes.
- Deserialize to whatever compressed bytes given.
- Serialize to whatever bytes are stored.
- Always pass verification
- Don't aggregate
Also updates `travis.yml` to test on release _and_ debug.
So this means that:
- `$ cargo test`: no signature verification.
- `$ cargo test --release`: signature verification
This was implemented because crypto in debug is veeeery slow (~100x slower than in release).
So now we have faster tests, but to be comprehensive you must also test in `--release`.
Open for discussion on this. Also for better ways to implement it.
=> Disable Signature verification in debug

README.md
Added `cmake` as a requirement for building lighthouse, as it is a dependency that must be installed on a fresh arch system.
Minor update to readme, to help anyone else installing a fresh system.
=> Listed Usage

eth2/types/src/attestation.rs, eth2/types/src/beacon_block.rs, eth2/types/src/beacon_block_header.rs, eth2/types/src/deposit_input.rs, eth2/types/src/slashable_attestation.rs, eth2/types/src/transfer.rs, eth2/types/src/voluntary_exit.rs, eth2/utils/ssz_derive/src/lib.rs, eth2/utils/ssz_derive/tests/test_derives.rs
https://github.com/sigp/lighthouse/issues/287
Lets the user annotate fields of a struct to skip for signed root
hashing.
=> Adding annotation capabilities to SignedRoot macro

.gitlab-ci.yml, .travis.yml, Dockerfile, eth2/state_processing/tests/tests.rs
Commands are added to the GitLab configuration file to enable it to sync built documentation to the S3 bucket.
Documentation will only be built from the master branch, and only updated when it is.
The AWS credentials are configured via GitLab variables, so they are kept secret.
=> GitLab autobuild lighthouse-docs & Improve Caching

README.md
Insecure `rustup` installation instructions.
Update to the README to suggest users to download and review the installation script prior to execution.
=> Update instructions to install rustup in README

beacon_node/client/src/client_config.rs
None.
Fixes the TODO in `main.rs` related to not supporting comma-separated bootnodes in the CLI.
I encountered this while setting up the Lighthouse image in the eth2 test runner.
Please provide any additional information. For example, future considerations
or information useful for reviewers.
=> Support multiple bootnodes

eth2/utils/bls/Cargo.toml, eth2/utils/bls/src/aggregate_public_key.rs, eth2/utils/bls/src/aggregate_signature.rs, eth2/utils/bls/src/lib.rs, eth2/utils/bls/src/public_key.rs, eth2/utils/bls/src/secret_key.rs, eth2/utils/bls/src/signature.rs
NA
Updates our BLS library:
- New version uses SHA2 instead of Keccak
- Pulls library from new library, instead of old archived one.
NA
=> Update BLS library

beacon_node/beacon_chain/Cargo.toml, beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/checkpoint.rs, beacon_node/beacon_chain/src/lib.rs, beacon_node/beacon_chain/src/persisted_beacon_chain.rs, beacon_node/client/src/beacon_chain_types.rs, beacon_node/client/src/client_config.rs, beacon_node/client/src/error.rs, beacon_node/client/src/lib.rs, beacon_node/eth2-libp2p/src/error.rs, beacon_node/network/src/beacon_chain.rs, beacon_node/network/src/error.rs, beacon_node/rpc/src/beacon_chain.rs, beacon_node/src/run.rs, eth2/fork_choice/src/bitwise_lmd_ghost.rs, eth2/fork_choice/src/lib.rs, eth2/fork_choice/src/longest_chain.rs, eth2/fork_choice/src/optimized_lmd_ghost.rs, eth2/fork_choice/src/slow_lmd_ghost.rs, eth2/fork_choice/tests/tests.rs, eth2/utils/fixed_len_vec/src/impls.rs, eth2/utils/slot_clock/src/lib.rs, eth2/utils/slot_clock/src/system_time_slot_clock.rs, eth2/utils/slot_clock/src/testing_slot_clock.rs, eth2/utils/ssz/src/decode.rs, eth2/utils/ssz/src/decode/impls.rs, validator_client/src/error.rs, validator_client/src/service.rs
NA
- Adds a `PersistedBeaconChain` struct.
- Allows `BeaconChain` to go to and from a `Store` via `PersistedBeaconChain`.
- Refactors some runtime components to accommodate loading the chain from the store.
- Does not persist the `op_pool`. I think this functionality is necessary and a future PR should introduce this feature.
=> Persist chain to store

eth2/utils/ssz/src/macros.rs
#385 SSZ ambiguous reference in tests module
FIx the execution of tests for nightly toolchain in SSZ modules
N/A
=> `ssz` is ambiguous (name vs any other name during import resolution)

eth2/utils/hashing/.cargo/config, eth2/utils/hashing/Cargo.toml, eth2/utils/hashing/src/lib.rs, eth2/utils/ssz/src/decode/impls.rs, eth2/utils/ssz/src/encode/impls.rs, eth2/utils/ssz/src/lib.rs
#404 
* added conditional support for `sha2` crate depending on target architecture
* added support for 32-bit architectures
=> Make SSZ compatible with `wasm32` targets

beacon_node/beacon_chain/Cargo.toml, beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/persisted_beacon_chain.rs, beacon_node/beacon_chain/src/test_utils.rs, beacon_node/beacon_chain/tests/tests.rs, eth2/operation_pool/Cargo.toml, eth2/operation_pool/src/attestation.rs, eth2/operation_pool/src/attestation_id.rs, eth2/operation_pool/src/lib.rs, eth2/operation_pool/src/max_cover.rs, eth2/operation_pool/src/persistence.rs, eth2/utils/boolean-bitfield/src/lib.rs, eth2/utils/ssz/src/decode/impls.rs, eth2/utils/ssz/src/encode/impls.rs, eth2/utils/ssz/tests/tests.rs
* Use a maximum coverage algorithm for attestations in the operation pool
* Refactor parts of the operation pool out into their own files
* Add support for persisting the operation pool to disk via `PersistedOperationPool`
* Disable checking of Merkle proofs in the operation pool, until we have a better story for handling deposits and ETH1 data
* ~Add a `MerkleTree` implementation to `merkle_proof` that will allow us to construct merkle trees for deposits, and read off proofs for them~
I wrote the `MerkleTree` library because I initially planned to construct `Deposit`s with valid proofs, and I wanted to test persisting them to/from the store. I gave up on that goal when I realised that `Deposit` handling needs a lot of work (see the comment on `get_deposits`), so now the `MerkleTree` is …
=> Op Pool: Max Cover and Persistence

beacon_node/network/src/sync/import_queue.rs, beacon_node/network/src/sync/simple_sync.rs, beacon_node/store/src/iter.rs
Resolves #412
- Simplifies logic for handling a `HelloMessage`.
- Changes the import queue to use a `HashMap` keyed by block root, instead of a `Vec`.
- Does not try to re-sync with a node when a parent hash is unknown but already in the import queue.
NA
=> Improve syncing, fix bugs

beacon_node/beacon_chain/Cargo.toml, beacon_node/client/Cargo.toml, beacon_node/eth2-libp2p/Cargo.toml, beacon_node/http_server/Cargo.toml, beacon_node/network/Cargo.toml, beacon_node/rpc/Cargo.toml, beacon_node/store/Cargo.toml, eth2/lmd_ghost/Cargo.toml, eth2/operation_pool/Cargo.toml, eth2/state_processing/Cargo.toml, eth2/types/Cargo.toml, eth2/utils/bls/Cargo.toml, eth2/utils/boolean-bitfield/Cargo.toml, eth2/utils/boolean-bitfield/fuzz/Cargo.toml, eth2/utils/fixed_len_vec/Cargo.toml, eth2/utils/ssz/Cargo.toml, eth2/utils/ssz/src/lib.rs, eth2/utils/ssz_derive/Cargo.toml, eth2/validator_change/Cargo.toml, tests/ef_tests/Cargo.toml, validator_client/Cargo.toml
Progress for #422
- Changes the package name of `ssz` to `eth2_ssz`
- Changes the package name of `ssz_derive` to `eth2_ssz_derive`
- Changes the crate-level docs in `ssz` to state that it's up-to-date with `v0.7.1` -- unions have been implemented and no other significant changes were made between `v0.6.3`. (Here's a [diff](https://github.com/ethereum/eth2.0-specs/compare/v0.6.3..v0.7.1) between the two spec versions, for reference)
The `ssz` and `ssz_derive` _package_ names have been changed to `eth2_ssz` and `eth2_ssz_derive`, however their _library_ names remain the same. This means that in `Cargo.toml` you import `eth2_ssz`, but in a `.rs` file you do `use ssz;`.
Additionally, the `eth2_ssz` package is in `eth2/utils/ssz` directory (the directory name does not match the package name, …
=> Prepare ssz for publishing on crates.io

account_manager/src/main.rs, validator_client/src/main.rs
- Default data directory for the account_manager, now points to ~/.lighthouse-validator, which is the same data dir as the validator binary.
This fixes #410
=> Fixed account_manager data dir

eth2/utils/tree_hash/Cargo.toml, eth2/utils/tree_hash/src/impls.rs, eth2/utils/tree_hash/src/lib.rs, eth2/utils/tree_hash/src/merkleize.rs, eth2/utils/tree_hash/src/merkleize_padded.rs, eth2/utils/tree_hash/src/merkleize_standard.rs, eth2/utils/tree_hash_derive/src/lib.rs, eth2/utils/tree_hash_derive/tests/tests.rs
Related to #432 
Add the `merkleize_partial` merkle root algorithm that is memory efficient when given large amounts of padding nodes. Spec `v0.8.0` has lots of padding nodes, so it makes sense to optimize for it.
Here's an sample from the Rust docs that describes this new algo:
```rust
/// ## CPU Peformance
///
/// A cache of `MAX_TREE_DEPTH` hashes are stored to avoid re-computing the hashes of padding nodes
/// (or thier parents). In effect, adding padding nodes only incurs one more hash per additional height
/// of the tree.
///
/// ## Memory Peformance
///
/// This algorithm has two interesting memory usage properties:
///
/// 1. The maximum memory footprint is roughly `O(V / 2)` memory, where `V` is the number of leaf
///    chunks with values (i.e., leaves that are not padding). …
```
=> Padding efficent merkle root algo

account_manager/Cargo.toml, beacon_node/Cargo.toml, beacon_node/beacon_chain/Cargo.toml, beacon_node/client/Cargo.toml, beacon_node/eth2-libp2p/Cargo.toml, beacon_node/http_server/Cargo.toml, beacon_node/network/Cargo.toml, beacon_node/rpc/Cargo.toml, beacon_node/store/Cargo.toml, eth2/lmd_ghost/Cargo.toml, eth2/state_processing/Cargo.toml, eth2/types/Cargo.toml, eth2/utils/boolean-bitfield/Cargo.toml, eth2/utils/eth2_config/Cargo.toml, eth2/utils/hashing/Cargo.toml, eth2/utils/ssz/Cargo.toml, tests/ef_tests/Cargo.toml, validator_client/Cargo.toml
Removes unused dependencies. Resolves #408 
Unused dependencies had to be removed manually. Currently there is no linting option for Rust 2018. Issue for unused dependencies lint https://github.com/rust-lang/rust/issues/57274
=> Remove unused dependencies

eth2/state_processing/src/per_block_processing/verify_transfer.rs
Addresses #421.
Verifying that the sender has adequate balance now compares against `total_amount` (_i.e._, `amount + fee`).
Supersedes #427.
=> Fix underflow in verify_transfer

beacon_node/network/src/service.rs
https://github.com/sigp/lighthouse/issues/435
- Split network and swarm discovery into two loops
- Both break when the interface is not ready.
Testing as mentioned in https://github.com/sigp/lighthouse/issues/435#issuecomment-514860338
> It is important to test to see there is no lag if we do this. Running two nodes with a single validator and watching blocks propagate instantly is a test that this should still work.
I hope the appraoch in the video (3 nodes, 1 validator) reflects that it does not seem to lag:
https://webm.red/C2U8.webm
=> Split network and swarm discovery loop, break each when not ready

.travis.yml, eth2/utils/logging/src/lib.rs
Resolves #473
- Adds a `cargo fmt` check to travis ci.
- Runs `cargo fmt --all` to fix some existing cargo fmt issues.
=> Add `cargo fmt` to .travis.yml

eth2/utils/ssz_types/src/bitfield.rs
Credit to @kirk-baird for finding the bug with the fuzzer.
=> Fix Bitfield from_bytes empty vec bug

eth2/utils/tree_hash/Cargo.toml, eth2/utils/tree_hash/benches/benches.rs, eth2/utils/tree_hash/examples/flamegraph_beacon_state.rs
NA
Adds some benches for tree hashing, as requested by @protolambda. We haven't put much effort into optimizing this, but it seems like the majority of the time is spent in sha2.
To run the benches, navigate to `eth2/utils/tree_hash` and run:
```
$ cargo bench
```
You can use [`cargo-flamegraph`](https://github.com/ferrous-systems/flamegraph) with:
```
$ cargo flamegraph --example flamegraph_beacon_state
```
Here's the output on my `i7-8700K CPU @ 3.70GHz`:
```
minimal/100000_validators/genesis_state
time:   [524.39 ms 535.79 ms 543.48 ms]
change: [+0.5340% +2.0554% +3.7095%] (p = 0.02 < 0.05)
Change within noise threshold.
minimal/300000_validators/genesis_state
time:   [1.5584 s 1.5698 s 1.5789 s]
change: [-1.8937% -0.9731% +0.0855%] (p = 0.10 > 0.05)
No change in performance detected. …
```
=> Tree hash benches

eth2/utils/ssz_types/src/bitfield.rs
When I was writing a test for #487 I noticed we seemed to allow extra bytes when decoding from SSZ, which [the spec implies is disallowed](https://github.com/ethereum/eth2.0-specs/blob/v0.8.2/specs/simple-serialize.md#deserialization).
(separate PR so that we can merge the other PR without resolving this discussion first, but also happy to roll them into one)
=> Disallow extra bytes in Bitfield from_bytes

eth2/state_processing/src/per_block_processing.rs, eth2/state_processing/src/per_block_processing/errors.rs, eth2/state_processing/src/per_block_processing/verify_deposit.rs, eth2/types/src/deposit_data.rs, eth2/types/src/test_utils/builders/testing_deposit_builder.rs, eth2/types/src/test_utils/test_random.rs, eth2/types/src/test_utils/test_random/public_key_bytes.rs, eth2/types/src/test_utils/test_random/signature_bytes.rs, eth2/utils/bls/src/lib.rs, eth2/utils/bls/src/macros.rs, eth2/utils/bls/src/public_key.rs, eth2/utils/bls/src/public_key_bytes.rs, eth2/utils/bls/src/signature.rs, eth2/utils/bls/src/signature_bytes.rs
SignatureBytes handles signatures stored in bytes and only parses the bytes when the signature is needed. Therefore SignatureBytes never throws errors except when the signature is parsed (which is then handled directly in verify_deposit.
resolves #384
Adds new struct SignatureBytes. Replaces Signature in Deposit by SignatureBytes.
=> Use SignatureBytes and PublicKeyBytes for deposits

README.md
None found
I've added the link to `env.md` in the README.md since it appears to be what was intended in the `Simple Local Testnet` section.
Install doc file got removed or never existed
=> fixed install docs link

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/fork_choice.rs, beacon_node/beacon_chain/src/iter.rs, beacon_node/beacon_chain/src/lib.rs, beacon_node/beacon_chain/src/test_utils.rs, beacon_node/network/src/sync/simple_sync.rs, beacon_node/rest_api/src/beacon_node.rs, beacon_node/rpc/src/attestation.rs, beacon_node/rpc/src/validator.rs, beacon_node/store/src/iter.rs, eth2/lmd_ghost/tests/test.rs
NA
Tidy the block and state root iterators on the `BeaconChain`:
- Renames `BeaconChain::current_state(..)` to `BeaconChain::speculative_state(..)`
- All iterators start at the head (best block). They never start on the speculative state anymore.
- The `Best...` iterators have been removed and their functionality replaced with `take_while()`.
NA
=> Tidy ancestor iterators

eth2/utils/ssz/README.md
#514 Badge was linked to the image of the badge and not the actual crate.
Fixed shield badge to link to the actual crate instead of the image of the badge.
=> Fix this link per @blacktemplar to link to the actual crate

eth2/utils/compare_fields_derive/src/lib.rs, eth2/utils/ssz_derive/src/lib.rs, eth2/utils/test_random_derive/src/lib.rs, eth2/utils/tree_hash_derive/src/lib.rs
Missing whitespace in the implementation of `TokenStream::to_string` on beta and nightly was breaking our parsing of derive macro attributes.
This change makes the parser ignore whitespace, and should make the beta and nightly builds succeed again.
Also adds a check on the `path` of the attribute, because I noticed that _all_ field attributes were being filtered, and this could have caused false positives if two attributes had the same inner identifier (something like `#[ssz(skip)]` and `#[tree_hash(skip)]`).
=> Robustify derive macro attribute parsing

beacon_node/network/src/message_handler.rs, eth2/state_processing/Cargo.toml, eth2/types/src/attestation.rs, eth2/types/src/attestation_data_and_custody_bit.rs, eth2/types/src/attester_slashing.rs, eth2/types/src/checkpoint.rs, eth2/types/src/crosslink.rs, eth2/types/src/deposit.rs, eth2/types/src/deposit_data.rs, eth2/types/src/eth1_data.rs, eth2/types/src/historical_batch.rs, eth2/types/src/pending_attestation.rs, eth2/types/src/proposer_slashing.rs, eth2/types/src/transfer.rs, eth2/types/src/validator.rs, eth2/types/src/voluntary_exit.rs, eth2/utils/tree_hash/Cargo.toml, eth2/utils/tree_hash_derive/src/lib.rs, protos/Cargo.toml, validator_client/src/attestation_producer/mod.rs, validator_client/src/block_producer/mod.rs, validator_client/src/duties/mod.rs
Lighthouse doesn't build with protobuf 2.9.0, and there's no point upgrading when it's about to be deleted.
=> Fix the build for Rust 1.38, protobuf releases

validator_client/Cargo.toml, validator_client/src/config.rs, validator_client/src/lib.rs
The `account_manager` generates private keys and stores them with unnecessary extensive permissions. Indeed, private keys are readable by any user of the system (i.e. `-rw-r--r--` or `0644` permission bits).
- Import libc crate for permission bits
- Change permissions on private key file generation to `-rw-------` (i.e. `0600`)
The validator client is about to be refactored, but thought I'd submit this now anyway :)
=> Change private key file permissions

README.md
No issue opened.
Small update to README to indicate that lighthouse is compliant with Eth2 v0.8.3.
=> Update README spec version.

eth2/utils/bls/Cargo.toml, eth2/utils/eth2_interop_keypairs/Cargo.toml
Remove the dependency on my fork of `milagro_bls` by using the new v0.11.0 release
=> Update Milagro BLS to v0.11.0

.gitignore, .gitlab-ci.yml, tests/ef_tests/Cargo.toml, tests/ef_tests/Makefile, tests/ef_tests/README.md, tests/ef_tests/src/handler.rs, tests/ef_tests/tests/tests.rs
* Re-jig the Makefile for downloading the EF tests so that the tarballs are separate targets, and can be cached
* Run `make` to download the EF tests before each relevant GitLab CI job
* Hide the EF tests behind a feature flag `ef_tests`. Make them fail if the test directory doesn't exist. Caveat: you need to run `cargo test --features ef_tests` if you want to run them locally.
Updating to a new version of the spec _should_ be as simple as bumping the version in the ef_tests Makefile and the `.gitlab-ci.yml`, which will cause the new tarballs to be downloaded afresh
Closes #527
=> Run EF tests on GitLab

beacon_node/beacon_chain/src/beacon_chain_builder.rs, eth2/utils/merkle_proof/src/lib.rs
This reverts commit 13faa47da14e5bad553bc98933f5e21311a87fc6 as it causes CI to fail.
=> Revert "Implement push_leaf for MerkleTree (#563)"

eth2/utils/swap_or_not_shuffle/benches/benches.rs, eth2/utils/swap_or_not_shuffle/src/compute_shuffled_index.rs, eth2/utils/swap_or_not_shuffle/src/lib.rs, eth2/utils/swap_or_not_shuffle/src/shuffle_list.rs, tests/ef_tests/src/cases/shuffling.rs
To match name of equivalent function in v0.8.3 spec.
No issue created.
Please list or describe the changes introduced by this PR.
Rename get_permutated_index to compute_shuffled_index.
Update relevant modules, docstrings.
I'm not aware of any external code that relies on this, so think it should be fine.
Whether this change is worth making is arguable, but happy for input.
=> Rename get_permutated_index to compute_shuffled_index.

eth2/utils/slot_clock/src/system_time_slot_clock.rs
NA
Allows slot clock to return a slot when it is exactly genesis time.
Attempting to fix a test fail experienced by @pscott.
=> Allow slot clock to work on genesis

Makefile
Fixes https://github.com/sigp/lighthouse/issues/578
- Create separate `test-ef` task and execute the normal `test` and `test-ef` when running `test-full`
=> Only run non-ef tests when executing make test

eth2/utils/eth2_hashing/Cargo.toml
eth2_hashing won't compile for wasm32 targets.
Add a dependency for wasm32 targets on the sha2 crate.
=> Depend on sha2 in eth2_hashing for wasm32

eth2/utils/merkle_proof/src/lib.rs
My bad: I didn't account for the clash with #574 when merging #584. This should fix the broken build.
=> Fix merkle_proof for eth2_hashing refactor

.gitlab-ci.yml
NA
Sets the gitlab docker image back to to `lighthouse:latest` after I set it (incorrectly) in the `eth1` PR.
=> Set the gitlab docker image to latest

lighthouse/src/main.rs, validator_client/src/cli.rs
- Removes unnecessary repetition of commands.
- Fixes a bug where we had a global field set as required (newer versions of clap don't like this).
=> Clean CLI arguments

beacon_node/eth2-libp2p/Cargo.toml, beacon_node/eth2-libp2p/src/behaviour.rs, beacon_node/eth2-libp2p/src/discovery.rs, beacon_node/eth2-libp2p/src/service.rs
The local ENR will automatically be updated based on the registered listen address given by libp2p
=> Enables ENR auto-update based on new listen address

beacon_node/eth2-libp2p/Cargo.toml
Corrects the reference to the latest `rust-libp2p` lighthouse branch
=> Update libp2p commit hash

account_manager/Cargo.toml, account_manager/src/cli.rs, account_manager/src/lib.rs, beacon_node/client/Cargo.toml, beacon_node/client/src/config.rs, lighthouse/Cargo.toml, lighthouse/environment/Cargo.toml, lighthouse/environment/src/lib.rs, lighthouse/src/main.rs, validator_client/Cargo.toml, validator_client/src/config.rs
NA
Removes the `account_manager` binary, place it's functionality under the `lighthouse binary`. 
Blocked on #542
=> Move account manager under main binary

beacon_node/eth2-libp2p/src/lib.rs, beacon_node/eth2-libp2p/src/rpc/codec/ssz.rs, beacon_node/eth2-libp2p/src/rpc/handler.rs, beacon_node/eth2-libp2p/src/rpc/methods.rs, beacon_node/eth2-libp2p/src/service.rs, beacon_node/network/src/message_handler.rs, beacon_node/network/src/service.rs, beacon_node/src/cli.rs, validator_client/src/config.rs
This PR waits a few hundred milliseconds before banning peers allowing protocols to finish negotiating and RPC messages to send goodbye messages before severing the connection. 
Additionally
- Corrects a deadlock in RPC handling
- Defaults validator client to ~ (mimicking the functionality of the beacon node)
- Removes unnecessary comments
- Sets the default for a testnet to 30 minutes
=> RPC Corrections and deadlock fix

beacon_node/eth2-libp2p/Cargo.toml
This updates our libp2p dependencies resolving security issues related to dependencies on an old version of `libsecp256k1`
=> Updates libp2p to v0.13

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/eth1_chain.rs, beacon_node/beacon_chain/src/fork_choice.rs, beacon_node/eth2-libp2p/src/behaviour.rs, beacon_node/eth2-libp2p/src/rpc/handler.rs, beacon_node/eth2-libp2p/src/rpc/mod.rs, beacon_node/eth2-libp2p/src/rpc/protocol.rs, beacon_node/eth2-libp2p/src/service.rs, beacon_node/network/src/lib.rs, beacon_node/network/src/message_handler.rs, beacon_node/network/src/service.rs, beacon_node/network/src/sync/manager.rs, beacon_node/network/src/sync/message_processor.rs, beacon_node/src/config.rs
This cleans up some of the logging around the network-specific functions. 
It removes unneccessary trace logs, applies clippy lints to `beacon_node` and corrects formatting.
=> Clean up network logging and code

beacon_node/eth2-libp2p/src/discovery.rs, beacon_node/eth2-libp2p/src/rpc/handler.rs, beacon_node/eth2-libp2p/src/service.rs
This adds a few minor corrections. 
- Corrects the Lighthouse ENR IP update logic
- Resets the `KeepAlive` timeout for the RPC on incoming connections (this realistically has no effect in lighthouse as gossipsub maintains a permanent connection) but it's added for logical consistency
- Corrects some formatting in discovery logs
=> Correct ENR update and log formatting

README.md
Ensures that the badge on the readme only refers to tests on the master branch. Presently it just refers to the latest test.
=> Specify master branch for CI badge

beacon_node/eth2-libp2p/Cargo.toml, beacon_node/eth2-libp2p/src/discovery.rs
Resolves Discv5 race condition for updating external IP addresses
Resolves Discv5 queries containing disconnected from never completing
Improves discovery logging
=> Add discv5 corrections

account_manager/Cargo.toml, beacon_node/Cargo.toml, beacon_node/eth1/Cargo.toml, beacon_node/eth2-libp2p/Cargo.toml, beacon_node/eth2-libp2p/src/behaviour.rs, beacon_node/eth2-libp2p/src/discovery.rs, beacon_node/eth2-libp2p/src/service.rs, beacon_node/genesis/Cargo.toml, beacon_node/network/Cargo.toml, beacon_node/network/src/service.rs, lighthouse/Cargo.toml, lighthouse/environment/Cargo.toml, tests/eth1_test_rig/Cargo.toml, validator_client/Cargo.toml
Instead of banning peers forever, this PR will only ban peers for 30 seconds. This is a segue to a more sophisticated reputation system. 
This PR updates and standardises some crate versions also
=> Implements a timeout for peer banning

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/rest_api/src/helpers.rs, beacon_node/rest_api/src/lib.rs, beacon_node/rest_api/src/validator.rs, beacon_node/rest_api/tests/test.rs, beacon_node/store/Cargo.toml, beacon_node/store/benches/benches.rs, beacon_node/store/examples/ssz_encode_state.rs, beacon_node/store/src/impls/beacon_state.rs, beacon_node/store/src/lib.rs, eth2/state_processing/src/per_block_processing.rs, eth2/state_processing/src/per_block_processing/signature_sets.rs, eth2/state_processing/src/per_block_processing/verify_deposit.rs, eth2/types/Cargo.toml, eth2/types/benches/benches.rs, eth2/types/examples/ssz_encode_state.rs, eth2/types/src/beacon_state.rs, eth2/types/src/beacon_state/pubkey_cache.rs, eth2/types/src/test_utils/builders/testing_beacon_state_builder.rs, eth2/types/src/validator.rs, eth2/utils/bls/src/lib.rs, eth2/utils/bls/src/macros.rs, eth2/utils/bls/src/signature_set.rs, eth2/utils/remote_beacon_node/src/lib.rs, validator_client/src/attestation_service.rs, validator_client/src/duties_service.rs
NA
Changes the type of `Validator.pubkey` to be `PublicKeyBytes` instead of `PublicKey` this saw a couple of orders magnitude decrease in the time it takes to SSZ decode the state.
=> Faster BeaconState enc/dec

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/builder.rs, beacon_node/beacon_chain/src/eth1_chain.rs, beacon_node/beacon_chain/src/test_utils.rs, beacon_node/beacon_chain/tests/persistence_tests.rs, beacon_node/beacon_chain/tests/store_tests.rs, beacon_node/client/src/builder.rs, beacon_node/src/lib.rs, beacon_node/store/src/block_at_slot.rs, beacon_node/store/src/chunked_iter.rs, beacon_node/store/src/chunked_vector.rs, beacon_node/store/src/forwards_iter.rs, beacon_node/store/src/hot_cold_store.rs, beacon_node/store/src/impls/beacon_state.rs, beacon_node/store/src/iter.rs, beacon_node/store/src/leveldb_store.rs, beacon_node/store/src/lib.rs, beacon_node/store/src/memory_store.rs, beacon_node/store/src/migrate.rs, beacon_node/store/src/partial_beacon_state.rs, eth2/lmd_ghost/src/lib.rs, eth2/lmd_ghost/src/reduced_tree.rs, eth2/lmd_ghost/tests/test.rs
Forwards block root iterators built upon #649
Likely to conflict with things because of the extensive refactoring of `Store` (now `Store<E>`).
=> Forwards block root iterators

beacon_node/client/src/notifier.rs
NA
Show two decimal places for syncing speed.
=> Add decimals display to notifier sync speed

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/metrics.rs, beacon_node/beacon_chain/src/test_utils.rs, beacon_node/beacon_chain/tests/tests.rs, beacon_node/network/src/sync/manager.rs, beacon_node/network/src/sync/message_processor.rs, beacon_node/network/src/sync/range_sync/chain.rs, beacon_node/rest_api/src/validator.rs
NA
Removes fork choice from `BeaconChain::process_block` and calls it on demand instead.
=> Less fork choice

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/builder.rs, beacon_node/beacon_chain/src/checkpoint_cache.rs, beacon_node/beacon_chain/src/lib.rs, beacon_node/beacon_chain/src/metrics.rs, beacon_node/store/src/impls/beacon_state.rs, eth2/types/benches/benches.rs, eth2/types/src/beacon_state.rs
NA
Adds basic caching of blocks/states to the beacon chain so it doesn't need to read the DB so much.
=> Add block/state caching on beacon chain

beacon_node/client/src/notifier.rs
NA
Takes the average sync times over 4 observations, instead of just observation-by-observation. Also displays the estimated sync time remaining.
=> Improve sync speed indicator

beacon_node/beacon_chain/tests/tests.rs
NA
Inspired by @arnetheduck in a Discord chat, this test ensures that we don't panic when we skip so far into the future that all validators are slashed.
Only adds a test, does not change actual "business" logic.
=> Add test for when skip slots remove all active validators

book/src/become-a-validator.md
If I understood correctly, this should help avoid misunderstanding of how long a sync might take.
(Another option may be a code change that log for INFO Syncing will display est_time first, before the distance.)
=> est_time for syncing is lower than distance

beacon_node/client/src/notifier.rs
- Resolves #687
- Closes #695
_Hopefully_ fixes an issue with `inf weeks NaN days` being printed by the slot counter.
=> Hopefully fix NaN issue in sync speed

beacon_node/beacon_chain/src/beacon_chain.rs
#692
We've been seeing a few issues with database inconsistency on the testnet, so this is a quick patch to hopefully address those issues. I'd like to address the issue more thoroughly once our choice of DB has settled down (or we come up with an API to abstract over atomic transactions in different DBs).
=> Store states in the DB before their blocks

beacon_node/beacon_chain/src/beacon_chain.rs
Closes #661 
Add a maximum slot limit after which we won't process incoming blocks anymore.
This number is 2^28 (`268_435_456`). If we let `SECONDS_PER_SLOT = 12` and `SECONDS_PER_DAY = 6400`, then we can see that `2^28 * 12 / 86400 / 365` ~= 102 years, or about the number of years first mentioned in #661 .
Fun fact, if we were to use 2^64, we'd be fine for about `7 019 309 008 260` years, or about 7 trillion years.
=> Add maximum slot limit when processing blocks

Dockerfile
Ran into issue with latest not pulling the correct version of rust.
Explicit definition of rust version number to be used.
=> Specify exact version for rust in Dockerfile

beacon_node/eth2-libp2p/tests/gossipsub_tests.rs
Closes #717. 
Reduces the num_nodes from 20 to 12.
Gossipsub has a configurable parameter `mesh_n_high` (default=12) for maximum peers in the gossipsub mesh for every topic. If the number of peers for any topic exceeds `mesh_n_high`, the protocol removes peers from the mesh to get back within the specified limit. The test was giving inconsistent results with `num_nodes = 20` as nodes were getting removed from the mesh before the gossipsub message was published to them. Changing it to 12 ensures we don't hit `mesh_n_high`.
Ran the test 100 times in debug and release and it terminated successfully every time.
=> Fix gossipsub test

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/client/src/builder.rs, beacon_node/rest_api/src/lib.rs, beacon_node/rest_api/src/metrics.rs, beacon_node/rest_api/src/router.rs, beacon_node/store/src/impls/beacon_state.rs, beacon_node/store/src/metrics.rs
* Cleans up the `BeaconState` overhead metrics so that they once again measure overhead.
* Adds new metrics for total time to read/write `BeaconState`s.
* Includes an extra call to the store in the `BLOCK_PROCESSING_DB_READ` metric.
* Adds a metric for the size of the freezer database.
=> Clean up database metrics, add freezer DB size

.github/workflows/test-suite.yml
NA
Adds the beacon chain simulator I built a while back into CI. The simulator:
- Creates a ganache CLI instance to simulate the eth1 chain.
- Deploys the deposit contract
- Submits a bunch of deposits
- Spins up 4x validator nodes, each with one validator client and an equal share of the previous deposits.
- Peers the nodes
- Ensures the nodes find genesis from the eth1 chain
- Allows the nodes to run for several epochs and uses the HTTP API to ensure they all finalize on the same things.
In effect, this is a quite comprehensive end-to-end test of the beacon node + validator client system.
=> Add simulator to CI

beacon_node/beacon_chain/src/beacon_chain.rs, tests/ef_tests/src/cases/sanity_blocks.rs
Closes #734 
- Ensured all EF tests were running with VerifyBulk
- Change the strategy in the `process_block_internal` function.
I had a look at other places where `BlockSignatureStrategy::VerifyIndividual` was used.
- It's used all over the place in the [`per_block_processing`](https://github.com/sigp/lighthouse/blob/master/eth2/state_processing/src/per_block_processing.rs) file. I believe this is desired?
- It's also used here https://github.com/sigp/lighthouse/blob/e7de1b3339818614b209049bc1bbdb4622aef06f/lcli/src/transition_blocks.rs#L67-L72  I don't know if this one should be changed?
- Finally it's used for benches here https://github.com/sigp/lighthouse/blob/e7de1b3339818614b209049bc1bbdb4622aef06f/eth2/state_processing/benches/benches.rs#L93-L115  Should this one be changed too?
=> Enable bulk signature verification

tests/beacon_chain_sim/src/local_network.rs
`beacon-chain-sim` was failing when some peers in the simulation couldn't successfully dial the bootnode and hence had 0 peers for the entire run. This happened if the node attempted to dial the bootnode before its enr was updated (when bootnode's enr contained `port = 0`). 
This PR sets the port number of the bootnode to some constant value instead having it as 0. This way, other nodes will always find the bootnode and can sync up the beacon state.
=> Fix simulator bug

Dockerfile
Addresses issue 748
Use multi-stage builds to save on the Docker image size.  (see https://docs.docker.com/develop/develop-images/multistage-build/ for more info)
This assumes that the rust image is going to continue to be debian:buster. It could be switched to alpine if you want to save another 60mb or so. But, some people like "bash" vs. "ash".
=> got Docker image down to 138mb from 1.8gb

Cargo.toml, beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/fork_choice.rs, beacon_node/beacon_chain/src/test_utils.rs, beacon_node/beacon_chain/tests/tests.rs, beacon_node/rest_api/src/helpers.rs, beacon_node/store/src/hot_cold_store.rs, eth2/state_processing/src/per_slot_processing.rs, lcli/src/transition_blocks.rs, lighthouse/Cargo.toml, tests/ef_tests/src/cases/sanity_blocks.rs, tests/ef_tests/src/cases/sanity_slots.rs
NA
Add an `Option<Hash256>` to `state_processing::per_slot_processing` that allows for passing in a state root when it is already known.
It is common that during per block processing we already know the state root of the parent state (because it is a field of the parent block). This optimization saves ~10-20ms on all block processing calls.
NA
=> Optimization: avoid recomputing known state roots

Cargo.lock, beacon_node/eth2-libp2p/Cargo.toml, beacon_node/eth2-libp2p/src/config.rs, lighthouse/Cargo.toml
This PR corrects a protobuf dependency within libp2p. 
This also updates gossipsub to the latest version. 
This PR enables all lighthouse nodes to anonymize their source `PeerId` when sending gossipsub messages.
=> Update libp2p and updates gossipsub

lcli/src/main.rs, lighthouse/environment/src/lib.rs, lighthouse/src/main.rs, tests/beacon_chain_sim/src/main.rs
Closes #740 
- Add `--log-format` option to enable users to specify their desired logging format.
- Add appropriate documentation
This option currently only supports the `JSON` format but I've set up the code to easily be able to add other formats.
=> Add log-format option to CLI

book/src/become-a-validator.md
I noticed this whilst addressing #771 
Updates the header about our testnet being down. We didn't end up announcing the testnet yet (however it has been up since the 22nd).
=> Update notice about testnet being down

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/builder.rs, beacon_node/beacon_chain/src/errors.rs, beacon_node/beacon_chain/src/lib.rs, beacon_node/beacon_chain/src/metrics.rs, beacon_node/beacon_chain/src/test_utils.rs, beacon_node/beacon_chain/src/timeout_rw_lock.rs, beacon_node/beacon_chain/tests/persistence_tests.rs, beacon_node/beacon_chain/tests/store_tests.rs, beacon_node/beacon_chain/tests/tests.rs, beacon_node/client/src/notifier.rs, beacon_node/network/src/message_processor.rs, beacon_node/network/src/sync/manager.rs, beacon_node/network/src/sync/network_context.rs, beacon_node/network/src/sync/range_sync/chain_collection.rs, beacon_node/network/src/sync/range_sync/range.rs, beacon_node/rest_api/src/beacon.rs, beacon_node/rest_api/src/error.rs, beacon_node/rest_api/src/helpers.rs, beacon_node/rest_api/src/validator.rs, beacon_node/rest_api/tests/test.rs
NA
Changes all read/write calls to the `BeaconChain` canonical head  `RwLock` to have timeouts. This is in response to a dead-lock discovered by @ppratscher.
Adding these timeouts don't resolve the core logic error that triggers the deadlock, but they should should:
- Stop the whole client from indefinitely locking when the deadlocks happen
- Assist in identifying the cause by creating error logs whenever they happen (instead of failing silently)
=> Add timeouts to canonical head rwlock

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/checkpoint_cache.rs
NA
Should remove a costly `BeaconState` clone during block processing. Unless Rust optimizes it out already..
=> Use Cow for checkpoint cache

Cargo.lock, beacon_node/eth2-libp2p/src/rpc/handler.rs, beacon_node/network/src/sync/range_sync/chain.rs
The network thread terminates streams if the application doesn't fulfil an RPC request in the allocated time. A peer would see a stream termination. If this occurs during a request for a range of blocks, it appears that a peer is malicious as it only sends a subset of blocks for the given request. 
This PR sends an error response before terminating the stream, allowing the requesting peer to identify a server error due to timeout. 
Additionally, on receiving an error, the inbound stream is now terminated, preventing an additional stream termination being sent to the application layer. 
The application layer should treat error responses as synonymous with stream terminations.
=> Improved RPC timeout handling

beacon_node/eth1/src/service.rs
Resolves #781
Turns out #781 was a bit of a false alarm, it was just a typo in the logs.
=> Fix typo in eth1 service logs

beacon_node/store/src/hot_cold_store.rs, eth2/state_processing/src/common/initiate_validator_exit.rs, eth2/types/src/beacon_state.rs, eth2/types/src/beacon_state/exit_cache.rs, tests/ef_tests/src/cases/epoch_processing.rs, tests/ef_tests/src/cases/operations.rs
Building the decompressed public key cache takes ~1s on the current testnet, and it was slowing down reconstruction of states in the database. When we replay blocks we don't check signatures and therefore don't need public keys, so the cache is unnecessary.
In the process I also fixed the exit cache so that the user gets an error if they forget to initialise it (and I added initialisation code in the one place where it is currently used). I changed the EF tests so they only pre-build the committee caches, and rely on the state processing code itself to initialise any other caches on-demand.
=> Avoid building caches during block replay

beacon_node/store/src/hot_cold_store.rs
This should hopefully fix the issues with forwards iterators while syncing. A variant of the `store_test`s with the `MainnetEthSpec` (sans `long_skip`) was confirmed to pass locally, but is too hefty for CI and is left for a future PR*.
Also, I tightened the check in `verify_slots_per_restore_point` so that it's compatible with the new succinct hot DB.
*Some unit tests for `get_latest_restore_point` and more testing of the store in general are also a priority
=> Fix off-by-one error in get_latest_restore_point

Cargo.lock, beacon_node/eth2-libp2p/Cargo.toml
Updates discv5 to use delay queue's to handle session and message timeouts. 
This PR fixes a bug where discovery never completes, leaving nodes stuck to their original peers.
Should also see speed improvements
=> Discv5 upgrade

beacon_node/src/cli.rs, beacon_node/src/config.rs, beacon_node/store/src/config.rs
This should reduce disk usage by 32x while keeping historical state queries to
less than 10s. If historical states are required quickly, the minimum SPRP of 32
can be set on the CLI.
=> Increase default slots per restore point to 2048

beacon_node/client/src/notifier.rs
Resolves #778 (hopefully)
Ensures that the notifier does not stop when an error is raised, instead it logs an error and keeps working for future times.
=> Notifier errors

Cargo.lock, beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/eth2-libp2p/src/rpc/handler.rs, beacon_node/network/src/message_processor.rs, beacon_node/network/src/service.rs, beacon_node/network/src/sync/network_context.rs, beacon_node/network/src/sync/range_sync/batch.rs, beacon_node/network/src/sync/range_sync/chain.rs, beacon_node/network/src/sync/range_sync/mod.rs, beacon_node/network/src/sync/range_sync/range.rs
Failed batches can create duplicate downloading chains for a single peer. That is, a peer is requested for a number of chains of blocks in parallel. 
This PR prevents this by only requesting blocks from peers if a current request is not already on-going.
This adds optimisations in the peer selection reducing the number of lookups.
This also reduces the batch size to 25, as there appear to be threading issues, were work being done on block processing prevents other threads (including libp2p negotiations) from progressing, leading to un-expected timeouts and network issues. 
This PR also downgrades some logging and comments out currently-excessive trace logs.
=> Sync fixes

Cargo.lock, beacon_node/eth2-libp2p/src/rpc/handler.rs
This corrects the delay queue handling of inbound RPC sub-streams. Previously, it was possible for an inbound RPC sub-stream to expire, then panic in the process of the stream closing when trying to remove the associated delay.
This closes #798.
=> Correct stream timeout delay queue handling

book/src/testnets.md
#795 
The docs in the lighthouse book has some outdated cli arguments. Remove the commands which aren't consistent with current version of lighthouse.
=> Remove outdated cli options from docs

eth2/operation_pool/src/lib.rs, eth2/operation_pool/src/max_cover.rs
None
- Remove Signature Verification on block production
When I ran tests locally I found out that this should be something like 1000x improvement on block production (scaling with the number of attestations in the op_pool...). 💃 
I would ask for the reviewer to make sure that disabling this verification will not cause any harm. I have checked twice for myself. The only place (that I'm aware of) where we call `op_pool.insert_attestation` is here:
https://github.com/sigp/lighthouse/blob/7396cd2cabb7f0a2e031ed6a4188e2a19bb7b331/beacon_node/beacon_chain/src/beacon_chain.rs#L1084-L1085
where we just verified that attestations had valid signatures
https://github.com/sigp/lighthouse/blob/7396cd2cabb7f0a2e031ed6a4188e2a19bb7b331/beacon_node/beacon_chain/src/beacon_chain.rs#L1048
I am pretty sure …
=> Optimize block production

beacon_node/eth2-libp2p/src/config.rs, beacon_node/eth2-libp2p/src/discovery.rs, beacon_node/src/cli.rs, beacon_node/src/config.rs
The CLI listen address was setting the discovery address. This meant that the ENR would never be loaded from disc and constantly be reloaded. 
Now, without specifying the discovery address in the CLI, previously saved ENR's with correct external IP's will be loaded by default, rather than replacing with a default and having to update once receiving pings from external peers.
=> Correct discovery address CLI functionality

beacon_node/eth1/tests/test.rs
None
- Fix typo in persist test name
- Fix clippy warning
One of the most useless PR ever, but I'm not sure I should include this typo fix in a different PR.
This will at least keep a clean merging history.
=> Fix typo in test name; fix clippy warning

beacon_node/eth2-libp2p/src/behaviour.rs
The gossipsub protocol content-addresses messages. It has an internal LRUCache which prevents duplicates of size 256. Lighthouse currently has the same. 
It is possible with large number of validators, voting on different heads to produce many more attestations than 256 in a single slot. If such a cycle (greater than 256 unique gossipsub messages) occur twice, the second will be re-propagated forming a loop which amplifies through the gossipsub network. 
Although further validation rules will be applied to objects in lighthouse before re-propagation, this PR increases the duplicates cache to 100,000 which will prevent such issues for non-malicious validator nodes < 100,000 (which should suit our current purposes).
=> Prevent duplicate gossipsub loops/message amplification

Cargo.lock, eth2/utils/eth2_hashing/src/lib.rs, eth2/utils/swap_or_not_shuffle/Cargo.toml, eth2/utils/swap_or_not_shuffle/src/compute_shuffled_index.rs, eth2/utils/swap_or_not_shuffle/src/lib.rs, eth2/utils/swap_or_not_shuffle/src/shuffle_list.rs
Removes a bunch of heap allocations during shuffling. These allocations were accounting for >25% of all allocations when running a 100k testnet for several hours.
=> Remove temporary heap allocations during shuffling

beacon_node/network/src/service/tests.rs
Address #871 
Change the `libp2p` and `discovery` ports in the `dht_persistence` test to some random number to avoid port clashes when tests are run.
We could also probably use the `unused_port` function here as an alternative to coming up with seemingly random port numbers for tests. https://github.com/sigp/lighthouse/blob/371e5adcf89d99a5958b802cf9925a990bd66ba6/beacon_node/src/config.rs#L602
=> Fix port conflict

beacon_node/store/src/hot_cold_store.rs
NA
I noticed there's a tree hash happening during block replay (I'm so deep in our heap now, I see and feel _all_ allocations, there is no escape).
This PR loads an extra block but saves a tree hash.
I only mildly know what I'm doing in the `Store`, @michaelsproul I'm sure you'll be keen to get your peepers on this.
=> Attempt to remove a tree hash from block replaying

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/rest_api/src/beacon.rs
#864 
Add checks for the existence  of `eth1_chain` before attempting to insert into the operation pool.
=> Add checks for eth1 chain connection before inserting to op pool

Cargo.lock, eth2/types/src/validator.rs, eth2/utils/ssz/Cargo.toml, eth2/utils/ssz/src/decode.rs, eth2/utils/ssz/src/encode.rs, eth2/utils/ssz/src/encode/impls.rs, eth2/utils/ssz_derive/src/lib.rs
NA
When observing `heaptrack` whilst running a non-validating lighthouse node for ~1hr, 25% of allocations (by count, not size) were in setting up the `SszDecoderBuilder` for the `state.validators` (not even actually decoding the fields). More than 10% were also used for builder allocations for `PendingAttestation`
This PR implements a new path in the derive macro that avoids the `SszDecoderBuilder` for fixed length items.
=> Add optimized SSZ decoding for fixed-len items

Dockerfile, lcli/src/deploy_deposit_contract.rs, lcli/src/helpers.rs, lcli/src/main.rs, lcli/src/new_testnet.rs
- Adds a command to `lcli` to generate a new testnet directory.
- Removes testnet directory creation from the deposit contract deploy command.
=> Add "new-testnet" command to lcli

beacon_node/beacon_chain/tests/store_tests.rs, beacon_node/store/src/hot_cold_store.rs, beacon_node/store/src/lib.rs
Closes #833
Introduces methods for easily deleting blocks and states from the hot database. This should enable us to prune irrelevant forks from the disk DB.
The `delete_block` method is necessary in order to clear the LRU cache
=> Add method to delete states from the database

Dockerfile, Makefile
NA
- Use `--locked` when using `cargo install` so the lockfile is respected (see https://github.com/rust-lang/cargo/issues/7169)
- Updates the Rust version in the Dockerfile.
=> Use --locked, upgrade Dockerfile Rust version

beacon_node/store/src/migrate.rs
I've been meaning to downgrade this log message for ages, and figured I'd make a PR while I remembered.
=> Less noisy logs for unaligned finalized blocks

beacon_node/network/src/sync/manager.rs
#822 
Updates the logic for how unknown block lookups function. This update has stricter rules on parent-block lookup chains. Chains will fail if any block in the chain cannot be processed. Peers will be downvoted if they send us a block that cannot be processed. 
This also randomises peers for block lookups.
=> Upgrade the parent lookup logic

eth2/types/src/test_utils/test_random/secret_key.rs, eth2/utils/bls/src/secret_key.rs
Master currently fails if `cargo update` is applied. The mock BLS key used to test ssz encoding is not of the correct range. The new BLS throws a panic and the test fails. 
This PR specifies a valid BLS key for the test.
=> Fix master failing test

book/src/http_network.md
902
It fixes a type in the documentation for network/peer_count endpoint at https://lighthouse-book.sigmaprime.io/http_network.html#networkpeer_count
=> fix typo in httpnetwork doc

book/src/docker.md
User's on discord has issues with docker and hitting the http api. 
The docs currently are misleading and will confuse users.
This updates the docs around docker allowing users to hit the http api server externally.
=> Book corrections to allow http api access for docker use

eth2/state_processing/src/per_epoch_processing/apply_rewards.rs
https://github.com/sigp/lighthouse/issues/920
* Divides by `EFFECTIVE_BALANCE_INCREMENT` both dividend and divisor on reward calculations
* Suffix `_ebi` on each effected variable (To avoid any future confusion)
* Reference https://github.com/ethereum/eth2.0-specs/pull/1635
=> Update reward calculations to v0.11.0 - Handle u64 overflow

Cargo.lock, beacon_node/beacon_chain/tests/attestation_tests.rs, beacon_node/beacon_chain/tests/store_tests.rs, beacon_node/beacon_chain/tests/tests.rs, beacon_node/eth1/src/service.rs, beacon_node/eth2-libp2p/Cargo.toml, beacon_node/eth2-libp2p/src/behaviour.rs, beacon_node/eth2-libp2p/src/config.rs, beacon_node/eth2-libp2p/src/discovery.rs, beacon_node/eth2-libp2p/src/lib.rs, beacon_node/eth2-libp2p/tests/common/mod.rs, beacon_node/eth2-libp2p/tests/gossipsub_tests.rs, beacon_node/network/src/persisted_dht.rs, beacon_node/network/src/service.rs, beacon_node/network/src/service/tests.rs, beacon_node/src/cli.rs, beacon_node/src/config.rs, eth2/operation_pool/src/lib.rs
This PR provides a number of updates to lighthouse and discv5
Lighthouse is now able to configure discv5 to fine-tune the DHT. This is done via a `Discv5Config`. This allows us now to tweak and modify discv5 from within lighthouse. 
This update also removes NAT'd peers from our DHT, which should make peer lookups significantly faster.
The logic for how a local ENR is created and handled is also modified. If no specific IP/PORT is given, then it does not get specified in the ENR, unless the ENR updates itself (which, by default, will only happen if the peer isn't behing a NAT).
We have extra CLI functionality to prevent the automatic ENR IP/PORT address modification for users wishing to use a fixed static known external IP/PORT.
=> Discovery v0.2.0 Update

Cargo.lock, beacon_node/beacon_chain/tests/attestation_tests.rs, beacon_node/beacon_chain/tests/store_tests.rs, beacon_node/beacon_chain/tests/tests.rs, beacon_node/eth1/src/service.rs, beacon_node/eth2-libp2p/Cargo.toml, beacon_node/eth2-libp2p/src/behaviour.rs, beacon_node/eth2-libp2p/src/config.rs, beacon_node/eth2-libp2p/src/discovery.rs, beacon_node/eth2-libp2p/src/lib.rs, beacon_node/eth2-libp2p/tests/common/mod.rs, beacon_node/eth2-libp2p/tests/gossipsub_tests.rs, beacon_node/network/src/attestation_service/mod.rs, beacon_node/network/src/persisted_dht.rs, beacon_node/network/src/service.rs, beacon_node/network/src/service/tests.rs, beacon_node/src/cli.rs, beacon_node/src/config.rs, eth2/operation_pool/src/lib.rs
The attestion service used a mix of seconds and slots for timing. This PR converts all time measurements to be measured relative to a slot to make testing easier. 
We can now test by adjusting the milliseconds_per_slot spec constant.
=> Attestation service slots

.github/ISSUE_TEMPLATE.md
There is no underlying issue addressed.
I propose to query the lighthouse and rust version in the Github issue template.
Usually, you always want to ask "Did you try turning it off and on again?" and "Which version/branch are you running?"
=> Github: Add version to issue template

tests/simulator/src/local_network.rs, tests/simulator/src/sync_sim.rs
The syncing sim had a race condition where it was reading nodes from  a RwLock without waiting for the write update. This meant that multiple nodes being added had the same node_id, which is really annoying to debug.
=> Fix race condition in the syncing sim

eth2/utils/eth2_testnet_config/src/lib.rs
NA
Fixes a bug where the path for loading the `genesis.ssz` file for the testnet directory was incorrect.
=> Ensure correct path for genesis state file

Cargo.lock, beacon_node/eth2-libp2p/Cargo.toml, beacon_node/eth2-libp2p/src/behaviour.rs, beacon_node/eth2-libp2p/src/discovery/mod.rs, beacon_node/eth2-libp2p/src/service.rs, beacon_node/eth2-libp2p/src/types/globals.rs, beacon_node/eth2-libp2p/src/types/topics.rs
This resolves #958. 
Updates all discovery queries to search for specific fork id and subnet searches now target specific subnets in ENR bitfields.
=> Updates all discovery searches to predicate searches

beacon_node/eth2-libp2p/src/behaviour.rs, beacon_node/eth2-libp2p/src/config.rs, beacon_node/eth2-libp2p/src/lib.rs, beacon_node/eth2-libp2p/src/rpc/methods.rs, beacon_node/eth2-libp2p/src/service.rs, beacon_node/eth2-libp2p/src/types/mod.rs, beacon_node/eth2-libp2p/src/types/pubsub.rs, beacon_node/eth2-libp2p/src/types/topics.rs, beacon_node/eth2-libp2p/tests/gossipsub_tests.rs, beacon_node/eth2-libp2p/tests/rpc_tests.rs, beacon_node/network/src/router/mod.rs, beacon_node/network/src/router/processor.rs, beacon_node/network/src/service.rs, beacon_node/network/src/sync/network_context.rs, beacon_node/network/src/sync/range_sync/batch.rs, beacon_node/network/src/sync/range_sync/chain.rs, beacon_node/rest_api/src/helpers.rs, beacon_node/src/cli.rs, beacon_node/src/config.rs
Updates the networking side to v0.11.0. 
- Removes `head-block-root` from `blocks_by_range` requests
- Modifies status message to use `fork_digest`
- Mixes in `fork-digest` into the `STATUS` RPC message
Updates fork upgrade logic to unsubscribe/re-subscribe on a fork change
Resolves #957
=> V0.11.0 network update

Cargo.lock, eth2/utils/slot_clock/Cargo.toml, eth2/utils/slot_clock/src/lib.rs, eth2/utils/slot_clock/src/manual_slot_clock.rs, eth2/utils/slot_clock/src/system_time_slot_clock.rs
Resolves #938
This PR is based off initial work by @michaelsproul.
The purpose is to provide functions for checking that blocks/attestations are within some slot range with a tolerance (`MAXIMUM_GOSSIP_CLOCK_DISPARITY`), as specified in the [v0.11.0 networking spec](https://github.com/ethereum/eth2.0-specs/blob/v0.11.0/specs/phase0/p2p-interface.md#global-topics).
=> Allow slot clock to handle clock disparity

Cargo.lock, eth2/utils/deposit_contract/Cargo.toml, eth2/utils/deposit_contract/src/lib.rs, lcli/Cargo.toml, lcli/src/check_deposit_data.rs, lcli/src/helpers.rs, lcli/src/main.rs, tests/eth1_test_rig/src/lib.rs, validator_client/src/validator_directory.rs
NA
Adds the `check-deposit-data` subcommand to `lcli`. It accepts a deposit amount and some deposit data and verifies that the deposit data can parse and that the root is valid.
It doesn't check the signatures, that can be done some other time.
I used [this transaction](https://goerli.etherscan.io/tx/0xccd6af654451597d2faa6f0b3032687c22bebc5c6c0a5119743e8ac073803dde) to produce this command:
```bash
lcli check-deposit-data 3200000000 0x22895118000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000120e98077dcc831ee842003df21bdfd8ff54df793ff6d82b98700ea434ac99ff54f0000000000000000000000000000000000000000000000000000000000000030936ba47084f31feda28cd052e0a15291 …
```
=> Add lcli tool for checking deposit data

beacon_node/src/cli.rs, beacon_node/src/config.rs
Addresses a comment raised here: https://github.com/sigp/lighthouse/issues/936#issuecomment-601142201
Enables the `--eth1` functionality when the `--eth1-endpoint` flag is supplied. It seems reasonable to assume that supplying an eth1-endpoint means you wish to use it.
=> Enable --eth1 flag when --eth1-endpoint is suppilied

beacon_node/beacon_chain/src/builder.rs, beacon_node/client/src/builder.rs, beacon_node/client/src/config.rs
NA
When trying to generate a genesis state from the eth1 chain, if the user exited before genesis had been found the next time they started an error would be returned saying there's no persisted beacon chain in the database.
This PR adds the following logic:
1. If the client is supposed to resume but there's no `PersistedBeaconChain` in the database, then use the `DepositContract` method to start.
1. _Always_ resume from the DB if it contains a `PersistedBeaconChain`.
(1) is not perfect, since it's possible that the user started with some other genesis method (e.g., `SszFile`) and then exited _just_ before the `BeaconChain` was created and persisted to disk. With this code, the next time they boot they'll be forced to the `DepositContract` start method. Fixing this edge case is …
=> Fix bug when resuming from DB prior to genesis

lcli/src/eth1_genesis.rs, lcli/src/main.rs
- Resolves #947
Don't override the genesis fork in the `lcli eth1-genesis` command. Before this fix, if the fork was different to `[1, 3, 3, 7]` then all deposits will be declared invalid and genesis will never trigger. This was a relic from before `GENESIS_FORK_VERSION` was included as a constant.
Also, allows for `--spec` as well as `-s`. I noticed that @q9f was using this on their [blog](https://dev.to/q9/how-to-run-your-own-beacon-chain-e70) but it wasn't supported by us. It makes sense, I added it.
I used the above blog post to generate the same testnet dir used by @q9f and successfully produced a genesis state. See below:
```
lcli eth1-genesis --eth1-endpoint https://rpc.goerli.mudit.blog/ --testnet-dir ~/.lighthouse/schlesi
2020-03-23 18:11:47,354 INFO  [lcli::eth1_genesis] …
```
=> Don't override the fork in `lcli eth1-genesis` 

beacon_node/network/src/attestation_service/mod.rs
duration_to_subscribe is being calculated as:
(duration_to_next_slot + slot_duration) * slots_until_subscribe
when it should be:
duration_to_next_slot + (slot_duration * slots_until_subscribe)
which was causing subscription messages to be produced late
=> order of operations fix in the duration_to_next_slot calculation

Cargo.lock, beacon_node/eth2-libp2p/Cargo.toml, beacon_node/eth2-libp2p/src/behaviour.rs, beacon_node/eth2-libp2p/src/config.rs, beacon_node/eth2-libp2p/src/types/pubsub.rs, beacon_node/eth2-libp2p/src/types/topics.rs, beacon_node/eth2-libp2p/tests/gossipsub_tests.rs
N/A
Adds snappy encoding/decoding to gossipsub messages. The default topic encoding that we subscribe to and publish on is set to `ssz_snappy`
=> Add snappy encoding to gossipsub messages

tests/simulator/src/cli.rs, tests/simulator/src/main.rs, tests/simulator/src/sync_sim.rs
Closes #943
Instead of checking after a given amount of epochs if nodes are in sync, check every epoch to complete faster
- With the latest tokio some portion of this could be reduced to using `any` (small refactor to consider for the future)
- The "are we synced yet" relies on checking if epochs are the same, instead of slots (keeping somehow the original logic) but this could later use the `node/syncing` endpoint
Also changes are small but I'm just becoming friends with Tokio Type combinators, so thanks for the patience with this
=> make sync sim end faster by checking sync every epoch

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/block_verification.rs, beacon_node/beacon_chain/src/lib.rs, beacon_node/beacon_chain/tests/import_chain_segment_tests.rs, beacon_node/network/src/sync/block_processor.rs, beacon_node/network/src/sync/range_sync/chain.rs
Closes #970
- Created a `ChainSegmentResult`, either `Successful` or `Failed`. In both cases it carries the info of number of `imported_blocks`, and in the failed case, the `BlockError`.
- Added `BatchProcessResult::Partial` to signal a failed batch with at least one successfully verified and imported block.
- Updated the logic to handle `BatchProcessResult::Partial`, as a summary:
- It removes all previous batches (mark as valid) and downvote peers using the same logic from the successful case. 
- Check if the batch can be retried using the same logic of the failure case.
- `process_chain_segment` no longer returns a `Vec` (`roots`), since it was only used to check its length. It returns instead the number of `imported_blocks`
- I added the logic of the partial processing result to the …
=> add handling of failed batches that imported blocks

beacon_node/beacon_chain/src/builder.rs, beacon_node/client/src/config.rs, beacon_node/src/cli.rs, beacon_node/src/config.rs
#829 
There's now a purge subcommand for the beacon node.  The user can run this when the chain_db gets in a bad state. The next time they run the client it will rebuild the chain_db.
This is my first-ever Rust PR, there may be better ways of doing these things so feel free to request changes / give feedback.
=> Added purge subcommand to purge beacon chain db

beacon_node/eth2-libp2p/src/config.rs, beacon_node/eth2-libp2p/src/service.rs, beacon_node/src/cli.rs, beacon_node/src/config.rs, book/src/local-testnets.md, lighthouse/src/main.rs
- Corrects issues with default UDP ports
- Displays the current data directory
- Updates the lighthouse book for setting up local testnets
Resolves #997
=> Update CLI defaults and book

beacon_node/eth2-libp2p/Cargo.toml, beacon_node/eth2-libp2p/src/lib.rs, beacon_node/eth2-libp2p/src/peer_manager/mod.rs, beacon_node/eth2-libp2p/src/peer_manager/peer_info.rs, beacon_node/eth2-libp2p/src/peer_manager/peerdb.rs, beacon_node/eth2-libp2p/src/types/globals.rs, beacon_node/eth2-libp2p/src/types/mod.rs, beacon_node/eth2-libp2p/src/types/sync_state.rs, beacon_node/network/src/router/mod.rs, beacon_node/network/src/router/processor.rs, beacon_node/network/src/service.rs, beacon_node/network/src/sync/manager.rs, beacon_node/network/src/sync/network_context.rs, beacon_node/network/src/sync/range_sync/chain.rs, beacon_node/network/src/sync/range_sync/chain_collection.rs, beacon_node/network/src/sync/range_sync/range.rs, beacon_node/rest_api/src/node.rs, beacon_node/rest_api/src/router.rs, book/src/http.md, book/src/http_node.md, eth2/utils/rest_types/src/lib.rs, eth2/utils/rest_types/src/node.rs
Connects the sync logic and manager to use the peer database and modify a global node sync state. 
Key functionality added:
- All Status'd peers now store a specific syncing state
- The node has an accessible sync state indicating the current state of the sync manager
- Two http API methods have been added: `/node/syncing`  and `/node/lighthouse_syncing`
This resolves #810
=> Global Sync access

beacon_node/eth2-libp2p/src/behaviour.rs, beacon_node/eth2-libp2p/src/discovery/mod.rs, beacon_node/eth2-libp2p/src/peer_manager/mod.rs, beacon_node/eth2-libp2p/src/peer_manager/peerdb.rs, beacon_node/eth2-libp2p/src/rpc/mod.rs
The peer manager needs to control the connection and disconnection of peers. Currently the manager lives on the global network behaviour. Because we are currently using a core-derive of libp2p we don't have access to behaviour events, such as when peers connect and disconnect. 
Previously the discovery behaviour had been handling this logic. As a workaround (while we upgrade to stable futures and write a custom global behaviour), the RPC injects messages into the global behaviour which then sends them to the peer manager. 
This logic will be updated once a custom behaviour is written.
=> Temporary integration of peer manager

Makefile, book/src/cli.md, book/src/local-testnets.md, lcli/src/main.rs
Minor usability updates.
- `lcli` is now a required binary for spinning up local testnets. This PR adds `lcli` to the makefile to be installed alongside lighthouse.
- Minor updates to the lighthouse book surrounding the creation of local testnets
=> Minor useability updates

beacon_node/eth2-libp2p/src/rpc/mod.rs, tests/simulator/src/sync_sim.rs
Updates the configs in the syncing sim to allow nodes to connect. 
This also adds RPC methods to inform the peer manager to add peers to the DB.
=> Correct issues with the syncing sim

beacon_node/eth2-libp2p/tests/common/mod.rs, beacon_node/eth2-libp2p/tests/gossipsub_tests.rs, beacon_node/eth2-libp2p/tests/noise.rs, beacon_node/eth2-libp2p/tests/rpc_tests.rs
Some tests appear to overlap on ports and fail CI non-deterministically. 
This shifts some of the tests to use random open ports. Although there is still a chance ports can clash (as some tests use sequential port numbers) the probability of clashes should be low enough that it doesn't warrant changing the tests to check for random ports for each node. 
Should CI continue to fail, a more rigorous method should be employed.
=> Shifts tests to use random ports

lcli/src/main.rs, lcli/src/new_testnet.rs
NA
`lcli new-testnet` was previously override spec default params with those that suit our testnets. Moving into multi-client territory, this is no longer desired.
With these changes `lcli --spec mainnet new-testnet` will produce a specification that matches [mainnet.yaml](https://github.com/ethereum/eth2.0-specs/blob/v0.11.1/configs/mainnet.yaml).
=> Fix defaults on lcli new-testnet

beacon_node/eth2-libp2p/Cargo.toml, beacon_node/eth2-libp2p/src/behaviour.rs, beacon_node/eth2-libp2p/src/config.rs, beacon_node/eth2-libp2p/src/types/pubsub.rs
Gossip message duplication has been increased in gossipsub lifting the burden from lighthouse. 
This is a temporary measure until we upgrade to stable futures and modify the underlying gossipsub
=> Shift gossip duplication into gossipsub

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/block_verification.rs, beacon_node/src/config.rs
NA
At the moment it's quite difficult to tell when a gossip block has been received since the logs are in `trace`. This adds a helpful `debug` message.
=> Add debug log when gossip block recieved

Cargo.lock, beacon_node/eth2-libp2p/tests/common/mod.rs, beacon_node/eth2-libp2p/tests/rpc_tests.rs, beacon_node/network/src/router/mod.rs, beacon_node/network/src/router/processor.rs
If a block's parent over gossipsub is not known it is dropped. A parent-lookup search should occur in this case. This PR updates to ensure parent lookups occur for blocks that have been gossiped.
=> Correct parent lookup

beacon_node/eth2-libp2p/Cargo.toml
An edge-case in discovery could cause a panic when running in debug. This also prevent early addition of nodes into the DHT.
=> Discv5 bug-fix

beacon_node/eth2-libp2p/src/rpc/codec/ssz.rs, beacon_node/eth2-libp2p/src/rpc/codec/ssz_snappy.rs, beacon_node/eth2-libp2p/src/rpc/protocol.rs
Closes #1000 a.k.a goodbye `unreachable`s
move names, versions, and encodings to be enums
I have the feeling these three should be mirrored in some decoding/de-serialization. If this is the case, could someone point me where?
=> Clean RPC names versions and encodings

beacon_node/eth2-libp2p/src/peer_manager/client.rs, beacon_node/eth2-libp2p/src/peer_manager/peer_info.rs, beacon_node/eth2-libp2p/src/peer_manager/peerdb.rs, beacon_node/eth2-libp2p/src/rpc/methods.rs, beacon_node/eth2-libp2p/src/types/globals.rs, beacon_node/rest_api/src/lighthouse.rs, beacon_node/rest_api/src/network.rs, beacon_node/rest_api/src/router.rs, book/src/http/lighthouse.md
Connects `PeerInfo` to the http api via two end points, 
- `lighthouse/peers` 
- `lighthouse/connected_peers`
These endpoints provide detailed peer information for known peers on the beacon node.
=> Additional HTTP API endpoints

Cargo.lock, account_manager/Cargo.toml, account_manager/src/deposits.rs, beacon_node/rest_api/src/helpers.rs, beacon_node/rest_api/src/validator.rs, eth2/types/src/attestation.rs, eth2/types/src/beacon_state.rs, eth2/types/src/selection_proof.rs, eth2/utils/clap_utils/src/lib.rs, validator_client/src/attestation_service.rs, validator_client/src/validator_directory.rs
NA
Make `lighthouse account deposited` wait until the eth1 node has finished syncing. This means that users who use this command before starting the VC can be confident that their eth1 node is synced and ready-to-go. This is also handy for our devops.
Also fixes a bug with testnet directory parsing where it was returning the wrong error if you specify a bad `--testnet-dir` flag.
=> Deposits wait

beacon_node/eth2-libp2p/src/lib.rs, beacon_node/eth2-libp2p/src/peer_manager/mod.rs, beacon_node/eth2-libp2p/src/peer_manager/peer_info.rs, beacon_node/eth2-libp2p/src/peer_manager/peer_sync_status.rs, beacon_node/eth2-libp2p/src/peer_manager/peerdb.rs, beacon_node/network/src/router/processor.rs, beacon_node/network/src/sync/block_processor.rs, beacon_node/network/src/sync/manager.rs, beacon_node/network/src/sync/mod.rs, beacon_node/network/src/sync/peer_sync_info.rs, beacon_node/network/src/sync/range_sync/chain_collection.rs, beacon_node/network/src/sync/range_sync/range.rs, tests/simulator/src/cli.rs, tests/simulator/src/sync_sim.rs
- Sync Handles peers that have a matching head slot but are on a forked chain
- Allows block parent lookup even when syncing
- Improves the syncing manager add_peer logic
- Adds further information into the peer status sync manager
- Minor corrections to the syncing sim
=> Update Syncing logic

eth2/utils/eth2_testnet_config/src/lib.rs, lcli/src/main.rs, lcli/src/new_testnet.rs
I have been creating a variety of testnet configurations. The `new-testnet` command refuses to overwrite any files in a current testnet directory. 
This PR allows lcli to overwrite files if the user provides the `--force` flag.
=> Allow lcli new-testnet to optionally overwrite files

beacon_node/Cargo.toml, beacon_node/beacon_chain/Cargo.toml, beacon_node/beacon_chain/src/block_verification.rs, lighthouse/Cargo.toml
This adds back a feature that allows us to write pre-state, post-state and block to disk . This feature existed before but got lost in a recent refactor. The only difference now is that the feature flag has been pushed up so it can be accessed from the `lighthouse` binary:
```bash
cd lighthouse
cargo run --release --features write_ssz_files -- beacon_node --http
```
=> Add feature flag for writing ssz pre/post to disk

eth2/types/src/chain_spec.rs, tests/ef_tests/tests/tests.rs
Fix an issue whereby some new fields of the chainspec weren't being plumbed through in `YamlConfig::from_spec`. Add a test that checks the `ChainSpec -> YamlConfig` direction of the mapping on the real `minimal` and `mainnet` configs
=> Fix mapping bug in YamlConfig

beacon_node/network/src/sync/range_sync/batch.rs, beacon_node/network/src/sync/range_sync/chain.rs, beacon_node/network/src/sync/range_sync/chain_collection.rs, beacon_node/network/src/sync/range_sync/range.rs
Closes #908 
- while changing chains, account for requested slots
- move from `BLOCK_PER_BATCH` to `EPOCHS_PER_BATCH` so that `blocks_per_batch = slots_per_epoch * epochs_per_batch` is always ` = 0 (mod slots_per_epoch)`
- in `get_next_batch` account for `start_slot` potentially being not an epoch boundary, and also making the last batch (that in which `target_head_slot` is contained) request at least one epoch of blocks. An example  If `slots_per_epoch = 5`, `epochs_per_batch = 2` (so that `blocks_per_batch = 10` ) and a chain with `start_slot = 3` and `target_head_slot = 23` the requested batches should be: `3->10, 10->20, 20->25` first one accounts for the start of the chain thus requesting 7 blocks, the second one is a regular middle batch requesting 10 blocks, and the last one is the …
=> Ensure batches align to epoch boundaries

beacon_node/genesis/src/eth1_genesis_service.rs, eth2/state_processing/src/genesis.rs, eth2/state_processing/src/lib.rs
- Resolves #1051
Ensures that genesis is not triggered to early.
Thanks for @q9f for picking this one up.
We should add some tests to find regression here, but I don't think that would be the best use of my time at this moment. I've raised in issue to track tests over at #1053.
=> Ensure genesis is not triggered too early

beacon_node/eth2-libp2p/src/config.rs
Removes the base64 padding when calculating gossipsub message ids
=> Remove padding from gossipsub ids

Cargo.lock, beacon_node/client/src/notifier.rs, beacon_node/timer/Cargo.toml, beacon_node/timer/src/lib.rs, beacon_node/websocket_server/Cargo.toml, beacon_node/websocket_server/src/lib.rs, eth2/utils/remote_beacon_node/Cargo.toml, eth2/utils/remote_beacon_node/src/lib.rs, lcli/src/deploy_deposit_contract.rs, lcli/src/main.rs
Ported the following to stable futures.
- `websocket_server`.
- `timer`.
- `spawn_notifer` in client.
- `eth2/utils/remote_beacon_node`
=> Port websockets, timer and notifier to stable futures

beacon_node/client/src/notifier.rs
N/A
Each slot can contain either a block or nothing at all. The normal `INFO` level sync log should display block hash if there is any or "empty" if there is none.
=> beacon/notifier: display block information for current slot

beacon_node/eth2-libp2p/src/behaviour.rs, beacon_node/eth2-libp2p/src/discovery/mod.rs, beacon_node/eth2-libp2p/src/peer_manager/client.rs, beacon_node/eth2-libp2p/src/peer_manager/mod.rs, beacon_node/eth2-libp2p/src/peer_manager/peerdb.rs, beacon_node/eth2-libp2p/src/rpc/codec/base.rs, beacon_node/eth2-libp2p/src/rpc/codec/mod.rs, beacon_node/eth2-libp2p/src/rpc/codec/ssz.rs, beacon_node/eth2-libp2p/src/rpc/codec/ssz_snappy.rs, beacon_node/eth2-libp2p/src/rpc/handler.rs, beacon_node/eth2-libp2p/src/rpc/methods.rs, beacon_node/eth2-libp2p/src/rpc/mod.rs, beacon_node/eth2-libp2p/src/rpc/protocol.rs, beacon_node/eth2-libp2p/tests/rpc_tests.rs, beacon_node/network/src/router/mod.rs, beacon_node/network/src/router/processor.rs
#990 
- Rewrite of the RPCErrors, and map them accordingly
- Send these errors to the peer manager, map them to reputation changes
- Update reputation on the peer manager according to their connection status and ban or unban peers wrt the minimum before ban
- Minor corrections addressing clippy lints
=> Connect RPC to Peer Manager

lcli/src/new_testnet.rs
Fixes an issue that stopped `lcli new-testnet` from setting the eth1 follow distance.
=> Fix typo in lcli new-testnet

lcli/src/main.rs, lcli/src/skip_slots.rs, lcli/src/transition_blocks.rs
NA
Allows `lcli` to take some SSZ encoded state, run `n` skip slots on it and output the resulting state.
=> Add skip-slots command to lcli

book/src/become-a-validator.md
- Resolves #1061
Adds an extra note to the "Become a Validator" docs to remind users to build from `testnet5`.
=> Add note about building from testnet5

beacon_node/eth1/src/service.rs
N/A
Degrade the `Imported eth1 block(s)` log message to `debug!` level.
I personally believe it's too noisy in the `info!` log. I don't have any hard feelings about this. If you believe this should be info-level, just reject my PR :)
=> beacon/eth1: degrade log to debug level

beacon_node/eth2-libp2p/src/peer_manager/mod.rs
This addresses #1106
Adds underflow checks to timing logic in the peer manager.
=> Protect against timing underflows

Cargo.lock, eth2/utils/eth2_testnet_config/.gitignore, eth2/utils/eth2_testnet_config/build.rs, eth2/utils/eth2_testnet_config/src/lib.rs, lighthouse/Cargo.toml, lighthouse/src/main.rs
NA
"Bakes in" the [schlesi](https://github.com/goerli/schlesi/tree/master/light) testnet by @q9f as the default testnet in lighthouse. This means that connecting to schlesi is achieved simply with:
```
lighthouse bn
May 06 10:06:09.451 WARN Ethereum 2.0 is pre-release. This software is experimental.
May 06 10:06:09.451 INFO Using default testnet                   default: schlesi-v0-11
...
```
=> Use schlesi as default testnet

beacon_node/beacon_chain/src/eth1_chain.rs, beacon_node/client/src/builder.rs, beacon_node/client/src/notifier.rs, beacon_node/eth1/src/service.rs, beacon_node/eth1/tests/test.rs, beacon_node/genesis/src/eth1_genesis_service.rs, beacon_node/src/lib.rs, lighthouse/environment/src/lib.rs, tests/node_test_rig/src/lib.rs
- Fixes eth1 `update_deposit_cache` and `update_block_cache` and eth1 tests
- Fixes `environment` to build proper tokio runtimes
- Port `node_test_rig` to stable futures
- Fix compile errors in beacon chain
- Refactor eth1 service update to mirror task spawning in validator_client
@AgeManning I have kept each fix as a separate commit so you can cherry-pick individual fixes. Most of them are just straightforward fixes except the eth1 service spawning refactor which I am not sure works the way we would expect it to.
=> stable futures fixes

beacon_node/src/cli.rs
NA
Removes the default value from the `--eth1-endpoint` flag so eth1 syncing doesn't always turn itself on.
=> Stop eth1 from always enabling

Cargo.lock, eth2/utils/eth2_key_derivation/Cargo.toml, eth2/utils/eth2_key_derivation/src/derived_key.rs, eth2/utils/eth2_keystore/tests/eip2335_vectors.rs, eth2/utils/eth2_keystore/tests/json.rs, eth2/utils/eth2_keystore/tests/tests.rs
NA
As pointed out by @kirk-baird, `rust_crypto` says that its hdkf expand/extract [must not be used for password hashing](https://docs.rs/rust-crypto/0.2.36/crypto/hkdf/index.html).
This PR uses [ring::hkdf](https://briansmith.org/rustdoc/ring/hkdf/index.html) instead.
=> Switch to ring for hkdf

tests/node_test_rig/src/lib.rs
`client.dummy_eth1_backend` has been assigned a value, in [the above line](https://github.com/ackintosh/lighthouse/blob/a310d0672e1939cb0f2a9456f14989e963f33db5/tests/node_test_rig/src/lib.rs#L77) already. 😃
=> Small fix: remove duplicated assignment

beacon_node/beacon_chain/src/observed_attestations.rs
NA
Moves some long-running tests over to debug.
I'm confident that running the tests in debug is not required to catch overflows.
=> Move long-running atestation tests to release

eth2/utils/eth2_wallet/tests/tests.rs
NA
Moves some long-running wallet tests over to release-only testing. They take several minutes on debug.
=> Move wallet tests to release only

beacon_node/beacon_chain/src/naive_aggregation_pool.rs, beacon_node/beacon_chain/src/test_utils.rs, beacon_node/beacon_chain/tests/store_tests.rs, beacon_node/beacon_chain/tests/tests.rs, beacon_node/rest_api/tests/test.rs
`assert_ne!` is preferred as it prints the values of expressions on panic. 😃
=> Tiny improvement: assertions

beacon_node/network/src/sync/range_sync/chain.rs, beacon_node/network/src/sync/range_sync/chain_collection.rs, beacon_node/network/src/sync/range_sync/range.rs
`remove_peer` in sync was removing the peer from the `peer_pool` of the first chain it finds. This caused issues where the removed peer from chain1 wasn't removed from chain2 and we ended up making requests to the disconnected peer which caused stalled syncs.
This PR modifies `remove_peer` to remove the peer from all existing head and finalised chains.
Tested this out while syncing Schlesi and don't see the sync stalling anymore.
=> Fix `remove_peer` in sync

beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/head_tracker.rs, beacon_node/beacon_chain/src/migrate.rs, beacon_node/store/src/errors.rs, beacon_node/store/src/hot_cold_store.rs, beacon_node/store/src/iter.rs, beacon_node/store/src/leveldb_store.rs, beacon_node/store/src/lib.rs, beacon_node/store/src/memory_store.rs
Fixes https://github.com/sigp/lighthouse/issues/1109
=> Race condition fix + Reliability improvements around forks pruning

validator_client/src/attestation_service.rs, validator_client/src/duties_service.rs, validator_client/src/is_synced.rs, validator_client/src/lib.rs, validator_client/src/notifier.rs
NA
Upgrade VC to use the new BN syncing endpoint. This allows it to have a much better notion of when it should/shouldn't request duties.
Note: any existing block/attestation production duties will still happen regardless of sync status.
=> Stable futures: Vc sync

Cargo.lock, beacon_node/beacon_chain/Cargo.toml, beacon_node/beacon_chain/src/attestation_verification.rs, beacon_node/beacon_chain/src/beacon_chain.rs, beacon_node/beacon_chain/src/block_verification.rs, beacon_node/beacon_chain/src/metrics.rs, beacon_node/beacon_chain/src/naive_aggregation_pool.rs, beacon_node/beacon_chain/src/observed_attesters.rs, beacon_node/network/Cargo.toml, beacon_node/network/src/lib.rs, beacon_node/network/src/metrics.rs, beacon_node/network/src/router/mod.rs, beacon_node/network/src/service.rs, eth2/state_processing/src/per_epoch_processing.rs, eth2/state_processing/src/per_slot_processing.rs, eth2/utils/lighthouse_metrics/src/lib.rs, tests/ef_tests/src/cases/sanity_slots.rs, validator_client/src/duties_service.rs
NA
- Fix a bug where the VC wasn't indicating when it is an aggregator.
- Make some changes to `NaiveAggregationPool` to make it less read-lock greedy.
- Makes `per_epoch_processing` return the `TotalBalances` struct
- @michaelsproul it would be great if you could check [this commit](https://github.com/sigp/lighthouse/pull/1151/commits/087cc6c9ec2b32c301bc7ae70c4d4a76ecc764a2) retrospectively, but it's non-substantive.
- Exposes many new metrics to Prometheus.
- Clean up some old unused metrics.
- I have not checked to see if this aligns with other clients metrics; I need this quicky and it can be aligned later. 
- These metrics will get a bit messy in the event of forking, but I don't see any way to keep this clean during forks.
- ~~Tests are failing on the upstream branch so they'll …
=> Stable futures: Fix VC bug, update agg pool, add more metrics

eth2/types/src/beacon_state/exit_cache.rs
Minor suggested cleanups after familiarising myself with the `ExitCache`.
* Remove "validators exiting/exited at a given epoch" comment in favour of the notion of exit epoch (less wishy-washy).
* Remove "or zero if not known" comment. The number of validators with that exit epoch is known, even in the case where it's zero.
* Rename `epoch` to `exit_epoch` for consistency and clarity.
* Rename `exits_per_epoch` to `exit_epoch_counts` for precision and clarity.
* Remove seemingly unnecessary complexity with `force_build`.
* Consider renaming `ExitCache` to `ExitEpochCache` for clarity.
=> Cleanup `ExitCache`

beacon_node/eth2-libp2p/src/rpc/codec/base.rs, beacon_node/eth2-libp2p/src/rpc/codec/ssz.rs, beacon_node/eth2-libp2p/src/rpc/codec/ssz_snappy.rs, beacon_node/eth2-libp2p/src/rpc/handler.rs, beacon_node/eth2-libp2p/src/rpc/methods.rs, beacon_node/eth2-libp2p/src/rpc/mod.rs
Corrects the RPC Error encdoing/decoding logic to use a container-less bytes for the error message
=> Correctly encode/decode RPC errors

beacon_node/eth1/src/service.rs
Seems that some duplicate code made it in (probably via `stable-futures` mega-merge). It brought back a noisy log that was removed by @q9f.
=> Remove duplicate code (and noisy eth1 log)

.github/workflows/test-suite.yml
Updates lighthouse's CI workflow to trigger on pull requests. 
As no-one is committing directly to master it makes sense we trigger on pull requests such that extern-contributors PR's have CI run on them and they are aware if their PR's are passing CI or not
=> Update work-flow for pull_request

consensus/state_processing/src/per_epoch_processing/apply_rewards.rs, consensus/types/src/eth_spec.rs, lcli/src/parse_hex.rs, lcli/src/skip_slots.rs, lcli/src/transition_blocks.rs
This PR fixes a bug in the calculation of rewards and penalties that was identified when the Schlesi testnet split on May 18th 2020.
The new code correctly produces a state with root `0xd2e0f469565e14d2eaa331d6d359062ce9162ffbb93d551c2428ef8489092f9b` when applying `block.ssz` from slot 150496 to the state `lh-pre.ssz`, downloadable here:
https://discord.com/channels/595666850260713488/707233122097299496/711935902468931595
This state root matches the pyspec and Teku, as per:
* https://discord.com/channels/595666850260713488/707233122097299496/711938830164295740
* https://discord.com/channels/595666850260713488/707233122097299496/711999231270977596
The root cause of the bug was an incorrect implementation of penalties for slashed validators who also targeted the correct root with their …
=> Fix Schlesi-splitting penalty bug

account_manager/src/wallet/create.rs, book/src/become-a-validator-source.md
"Important" was meant instead of "import".
=> Minor fix on wallet output text

book/src/become-a-validator-source.md, book/src/installation.md
NA
Now that Schlesi has passed away (RIP) we don't need to maintain compat. with the old validator keys. This PR removes the instruction for users to install via the `v0.1.2` tag.
=> Remove v0.1.2 install instructions

beacon_node/beacon_chain/src/attestation_verification.rs, beacon_node/beacon_chain/src/block_verification.rs, beacon_node/beacon_chain/src/errors.rs, beacon_node/beacon_chain/src/eth1_chain.rs, beacon_node/beacon_chain/src/fork_choice.rs, beacon_node/beacon_chain/tests/attestation_verification.rs, beacon_node/beacon_chain/tests/block_verification.rs, beacon_node/beacon_chain/tests/persistence_tests.rs, beacon_node/beacon_chain/tests/store_tests.rs, beacon_node/beacon_chain/tests/tests.rs, beacon_node/store/src/errors.rs, beacon_node/store/src/lib.rs
This has been salvaged from the [failed attempt at replacing MemoryStore with plain LevelDB](https://github.com/sigp/lighthouse/issues/1139#issuecomment-630976898).
The reason why reliance on `PartialEq` with error types is risky is that some error types are merely *tokens* for actual errors and can't capture the complete context the error values represents as it lies partially in the OS ([std::io::Error](https://doc.rust-lang.org/std/io/struct.Error.html) for instance).  If the error value doesn't capture the entire context, `==` on it isn't well defined.  It's therefore safer to *match* against specific `Err(...)`, rather the `==` the value assuming it implements `PartialEq`, and this is what this PR changes.
In addition to he above, the requirement on error type to be `PartialEq` …
=> Relax PartialEq constraint on error enums

beacon_node/network/src/attestation_service/mod.rs, beacon_node/network/src/attestation_service/tests.rs
Fixes inconsistent tests from #1070. 
Tests were failing when random subnet discoveries happen to be for the same subnet as the exact subnets specified in the scenario. This would cause fewer messages to be produced than expected and the scenario to fail. This change makes it so we don't compare exact subnet subscription messages when fewer than the expected number of messages are produced.
=> fix attestation service tests

Cargo.lock, beacon_node/rest_api/Cargo.toml, beacon_node/rest_api/tests/test.rs
This is the first PR for #914.
I've added tests that ensures `/validator/attestation` returns `400 Bad Rquest` if the required query parameters are missing in the request.
=> Add tests for REST API `/validator/attestation`

beacon_node/store/src/hot_cold_store.rs, beacon_node/store/src/lib.rs
Removes a layer of indirection in the database access code making it easier to understand and refactor.  This is a step toward improving atomicity.
=> Ditch StoreItem trait

Cargo.lock, beacon_node/client/Cargo.toml, beacon_node/client/src/notifier.rs, beacon_node/eth1/src/service.rs, beacon_node/genesis/src/eth1_genesis_service.rs, beacon_node/genesis/src/lib.rs
- Resolves #1186
- Resolves #1178
Applies the following to `Eth1GenesisService`:
- Fixes a bug where genesis was being triggered too late.
- The candidate `BeaconState` was using `eth1_block.timestamp` as the genesis time, not `eth2_genesis_time(eth1_block.timestamp)`.
- Increases polling speed when we're trying to catch up to the eth1 head
- Previously all polling happened at 7s intervals, this made it quite slow to catch up to the head.
- Improves logging UX.
- Adds an `Eth1GenesisService::statistics` method which returns statistics useful for future HTTP API upgrades.
- Removes unnecessary clones.
=> Improve genesis service

lighthouse/src/main.rs
This is a temporary work around for ending lighthouse, once all tasks are complete.
The original behaviour was to wait until all tasks have been completed before ending the client. This was upgraded to waiting a maximum period of time for tasks to complete before forcing a shutdown. This upgraded behaviour does not work as expected due to a bug in tokio. 
I've reverted to the old behaviour, as a temporary work-around.
This speeds up lighthouse's shutdown time making it super fast (as it should be). We will revert to having a maximum wait time once the bug in tokio is fixed. For now, this should be good for public use.
=> Drop runtime after task completion

Cargo.lock, account_manager/Cargo.toml, beacon_node/eth1/Cargo.toml, beacon_node/eth2-libp2p/Cargo.toml, beacon_node/eth2-libp2p/src/discovery/mod.rs, lcli/Cargo.toml, testing/eth1_test_rig/Cargo.toml, validator_client/Cargo.toml
This allows Lighthouse to discover and connect to peers that have a differing `next_fork_version` in their ENR `eth2` fields. Specifically we only match on `fork_digest` when searching for compatible peers. 
This also updates dependencies for the eth2-libp2p crate, including some discovery and ENR fixes.
=> Allow discovery to be more lenient in enr eth2 fields

lighthouse/environment/src/lib.rs, lighthouse/src/main.rs
This reverts #1196. 
Although #1196 worked in some cases (including my test runs) it does not work in general. I've shortened the wait time to 2 seconds, but again this is not ideal. We will have to wait for an upstream fix for this to be corrected properly.
=> Revert runtime drop

account_manager/src/common.rs, account_manager/src/wallet/create.rs
Issue #1175 
* Add a function to `src/common.rs` that strips off newline chars (`\n` and `\r`)
* Characters are stripped off from the end until the first non-newline character is found
* This newly added function is tested in `src/common.rs` 
* Use this function before parsing bytes as `PlainText` in `src/wallet/create.rs`
The mutability of read bytes is changed to `mut` to be able to strip off the characters.
=> Strip off newline chars from password

Cargo.lock, beacon_node/eth2-libp2p/src/service.rs
Use spec compliant `X25519Spec` keys instead of `X25519`.
=> Upgrade to spec compliant noise protocol

Cargo.lock, beacon_node/eth2-libp2p/src/rpc/handler.rs
It is possible that the RPC threads do not wake to complete a stream send flush and close. Upon re-waking the thread will complete the task, but if there is no event to wake the thread the task can remain uncompleted indefinitely. 
This PR ensures that RPC events are driven to completion before the handler task becomes idle.
=> Drive RPC streams to completion

Cargo.lock, beacon_node/beacon_chain/Cargo.toml, beacon_node/beacon_chain/src/events.rs, beacon_node/client/Cargo.toml, beacon_node/client/src/builder.rs, beacon_node/rest_api/Cargo.toml, beacon_node/rest_api/src/beacon.rs, beacon_node/rest_api/src/error.rs, beacon_node/rest_api/src/lib.rs, beacon_node/rest_api/src/router.rs, beacon_node/src/lib.rs
* Implements [forks streaming](https://ethereum.github.io/eth2.0-APIs/#/Beacon/get_beacon_fork_stream) via [Server Sent Events mechanism](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events), based on the Hyper library.  Other streaming endpoints to follow.
* First head seen by the validator client is the one beacon node saw changed first *after* the connection to `/beacon/fork/stream` was made.
* ~~(!) Disables the current WebSockets endpoint.  I.e. it no longer publishes events.  This is not final.  I'm gonna need a decision here what to do with it: whether to try to maintain both, or to ditch WebSockets completely.~~
* Uses a thread per connection.  This may sound expensive but I don't anticipate more than 1-2 clients connected.  In any case, it …
=> Add first Server Sent Events API endpoint

account_manager/src/validator/deposit.rs
#1204
Please list or describe the changes introduced by this PR.
There's probably a cleaner way to do this that doesn't duplicate code? I just rushed this out since witti launced and i wanted to use it. Tested this on my home setup where the goerli node & beacon node & validator node are all separate nodes and it worked!
https://goerli.etherscan.io/address/0xa98eb1b501d9c6d328c63c0dcf26e6d11045e489
All 5 transactions for the validators were successfully sent & confirmed :)
=> Deposit functionality now works with IPC & RPC

beacon_node/operation_pool/src/lib.rs, consensus/proto_array_fork_choice/src/proto_array_fork_choice.rs
This PR fixes possible deadlock bugs in beacon_node/operation_pool and consensus/proto_array_fork_choice.
Both are in fn `eq(&self, other: &Self)`.
When `self` and `other` refers to the same obj, (i.e. comparing with itself),
the first Read lock is not released before calling the second Read lock. 
The lock is a `parking_lot::RwLock`.
According to the doc of `parking_lot::RwLock`:
[“readers trying to acquire the lock will block even if the lock is unlocked when there are writers waiting to acquire the lock.”
“attempts to recursively acquire a read lock within a single thread may result in a deadlock.”](https://amanieu.github.io/parking_lot/parking_lot/struct.RwLock.html)
Therefore, a deadlock may happen when a write lock interleaves the two read locks.
This PR compares the ptr addresses …
=> beacon_node, consensus: fix possible deadlocks when comparing with itself

beacon_node/eth2-libp2p/src/peer_manager/peerdb.rs, beacon_node/eth2-libp2p/tests/gossipsub_tests.rs, beacon_node/eth2-libp2p/tests/rpc_tests.rs
- Increases the timeout of RPC tests as CI was showing occasional failures. 
- Removes gossipsub tests - These have been occasionally failing and need to be re-worked for gossipsub 1.1. They are currently commented out to re-use in a future update.
- Cleans up debug logging in the peer manager.
=> Cleanup logs, increase test timeouts, remove gossipsub tests

beacon_node/network/src/sync/manager.rs, beacon_node/network/src/sync/peer_sync_info.rs
This is an optimisation which handles a syncing edge case where a node sends a status just as it gets a new block which creates a new finalized epoch. 
In this state, the peer's finalized epoch is greater than our own and we begin range sync, even though the peer may be only 1 slot ahead. 
This prevents the long-range sync and considers the peer synced.
=> Handle syncing edge case

beacon_node/eth2-libp2p/tests/rpc_tests.rs
Increase timeouts in RPC tests to handle slow CI
=> Increase RPC test timeouts

.github/workflows/test-suite.yml, Cargo.lock, Makefile, account_manager/Cargo.toml, beacon_node/Cargo.toml, beacon_node/network/Cargo.toml, beacon_node/store/Cargo.toml, common/compare_fields/Cargo.toml, common/validator_dir/Cargo.toml, consensus/proto_array_fork_choice/Cargo.toml, consensus/ssz_types/Cargo.toml, consensus/state_processing/Cargo.toml, consensus/swap_or_not_shuffle/Cargo.toml, consensus/types/Cargo.toml, crypto/bls/Cargo.toml, lcli/Cargo.toml, lighthouse/environment/Cargo.toml, testing/ef_tests/Cargo.toml, validator_client/Cargo.toml, validator_client/slashing_protection/Cargo.toml
None
Remove unused crates from the dependency graph, and run `cargo udeps` on CI so that we keep Lighthouse as light as possible!
=> Check for unused deps in CI

beacon_node/beacon_chain/src/migrate.rs
NA
- Bypass pruning finalized blocks/states if there is only a single head in the chain. 
When running `heaptrack` during a Witti sync I noticed a significant amount of allocations 5.5GB in ~1 minute (12.8% of total allocations) due to trying to prune a single head:
[![pruning.png](https://i.postimg.cc/jdt1YP8y/pruning.png)](https://postimg.cc/jC3czwYj)
It's rebuilding the `TreeHashCache` due to needing to replay blocks that's actually doing all the allocation. Ideally it would be good to be able to access non-boundary hot states without doing a tree-hash, but that's non-trivial. Even if we had that, I think this change would still be worth it.
After this change I can't even see anything related to pruning on the flamegraph, so I assume it is effective.
=> Avoid pruning when there are no forks

beacon_node/Cargo.toml, beacon_node/src/config.rs
Removes the configuration file for the beacon chain. 
This simplifies the CLI which often had incorrect logic flows due to optionally saving and re-loading the configuration file.
=> Remove beacon-chain config file

beacon_node/Cargo.toml, beacon_node/eth2_libp2p/src/config.rs, beacon_node/eth2_libp2p/src/discovery/mod.rs, beacon_node/eth2_libp2p/src/service.rs, beacon_node/src/cli.rs, beacon_node/src/config.rs
Make the discovery service optional. Useful for managing and strictly controlling the peers connected to lighthouse.
=> Optional Discovery

Cargo.lock, Cargo.toml
NA
Switches to a different `leveldb` that searches `lib64` directories for shared libraries.
=> LevelDB CMake hotfix

consensus/types/src/selection_proof.rs
NA
Uses `hash` instead of `tree_hash` for `is_aggregator`.
See: https://github.com/ethereum/eth2.0-specs/blob/v0.12.1/specs/phase0/validator.md#aggregation-selection
=> Swap hasher for is_aggregator

Cargo.lock, Makefile, beacon_node/beacon_chain/src/observed_attesters.rs, beacon_node/beacon_chain/src/test_utils.rs, beacon_node/eth2_libp2p/src/behaviour/handler/delegate.rs, beacon_node/eth2_libp2p/src/behaviour/handler/mod.rs, beacon_node/eth2_libp2p/src/behaviour/mod.rs, beacon_node/eth2_libp2p/src/discovery/mod.rs, beacon_node/eth2_libp2p/src/peer_manager/mod.rs, beacon_node/eth2_libp2p/src/rpc/handler.rs, beacon_node/network/src/attestation_service/mod.rs, beacon_node/network/src/router/mod.rs, beacon_node/network/src/service.rs, beacon_node/network/src/sync/manager.rs, beacon_node/rest_api/src/validator.rs, beacon_node/src/config.rs, common/eth2_testnet_config/build.rs, common/validator_dir/src/builder.rs, consensus/proto_array_fork_choice/src/fork_choice_test_definition.rs, consensus/proto_array_fork_choice/src/fork_choice_test_definition/ffg_updates.rs, consensus/proto_array_fork_choice/src/fork_choice_test_definition/no_votes.rs, consensus/proto_array_fork_choice/src/fork_choice_test_definition/votes.rs, consensus/types/src/beacon_block.rs, crypto/eth2_keystore/src/keystore.rs, lighthouse/environment/src/lib.rs, validator_client/src/duties_service.rs
None
Fix clippy's [performance lints](https://rust-lang.github.io/rust-clippy/master/index.html).
The `make lint` command currently doesn't check for anything:
https://github.com/sigp/lighthouse/blob/da6ab85e9908959f370af9f3fb2a33c7460bac7a/Makefile#L53-L56
I don't believe any crate adds any lints anywhere. 
It could be a good idea to have **at least** performance lints on by default?
I can imagine that having `clippy::pedantic` linting level by default might be cumbersome (~~though I would personally enforce it, but I'm anal haha~~), but I think that having performance lints by default for Lighthouse would make sense :)
EDIT: after https://github.com/sigp/lighthouse/pull/1286/commits/a8f994be3682e14d2f44da21d87e29fc5f087cc1, closes #1287 :)
=> Fix clippy's performance lints

beacon_node/network/src/attestation_service/mod.rs, beacon_node/network/src/metrics.rs
This is helpful for some debugging I'm doing; I can't see any unaggregrated attestations coming and I want to know if there are any subscriptions reaching the BN.
=> Add metrics for validator subscriptions

beacon_node/network/src/attestation_service/mod.rs
Subscriptions can create events that need to be sent to the network threads to execute.  The events being generated do not wake the attestation service thread for the network service to obtain the events. 
This PR adds a manual waker to inform the network thread to check the attestation service once a subscription has been processed. 
This corrects issues where attestation service messages are not being poll'd.
=> Add waker to attestation service

beacon_node/eth1/src/service.rs, beacon_node/eth1/tests/test.rs, beacon_node/genesis/src/eth1_genesis_service.rs
..None? :D
Replace `service: Self` in the function signature under `eth1/service` with `&self` in most cases and with `self` in the `auto_update` function. This removes the need for a few clones, which should be a perf improvement.
(Figured I'd make a small change as I'm slowly navigating through the repository)
=> fix(eth1/service): use self instead of Service

beacon_node/genesis/src/eth1_genesis_service.rs, consensus/state_processing/src/genesis.rs, consensus/types/src/beacon_state.rs, consensus/types/src/beacon_state/tests.rs
#922 
get_active_validator_indices now returns an EpochOutOfBounds error if the requested epoch is >= compute_activation_exit_epoch(current_epoch)
see issue for discussion
=> get_active_validator_indices() now has bound check

Cargo.lock, beacon_node/eth2_libp2p/Cargo.toml, beacon_node/eth2_libp2p/src/service.rs
This introduces a hack that brings our noise handshake protocol to spec. 
This also adds back our secio fallback support to ensure we are maximally compatible for the up coming testnet.
=> Temporary noise fix

beacon_node/eth2_libp2p/src/rpc/methods.rs, beacon_node/eth2_libp2p/src/rpc/protocol.rs
Duplicate #1293 
The ssz bounds were being calculated incorrectly for BlocksByRootRequest as we were counting the size of the ssz container as well. Fixes that to calculate bounds directly on the VariableList type. 
Must have gotten deleted while merging specv012 to master.
=> Fix BlocksByRootRequest min/max bounds calculation

common/validator_dir/src/manager.rs, common/validator_dir/src/validator_dir.rs, validator_client/src/cli.rs, validator_client/src/config.rs, validator_client/src/lib.rs
NA
- Adds a `--strict` flag which, when present:
- Requires that validator directories do not have lockfiles present.
- Requires the `--auto-register` command to add new validators to the slashing DB.
In effect, what we currently do (without this PR) is the same as using `--strict`. So, this PR loosens those restrictions by default.
This is fundamentally a temporary workaround for #1313, with the `--auto-register` change thrown-in for good measure.
=> Loosen VC lockfile and slashing protection registers

beacon_node/eth2_libp2p/src/discovery/mod.rs
This PR fixes the comparison operators issue. 
Let's say we don't allow retrying (`MAX_DISCOVERY_RETRY`: 0): the first querying (retry: 0) should be allowed and the first retry (retry: 1) should not be allowed.
=> Fix a retry limit condition

consensus/fork_choice/src/fork_choice.rs, consensus/fork_choice/tests/tests.rs
- Resolves #1315
Fixes a bug in fork choice verification that was incorrectly verifying `attestation.data.target.root` when the `attestation.data.beacon_block_root` is from a prior epoch to `attestation.data.target.epoch`.
NA
=> Fix invalid attestation verification condition

Cargo.lock, common/deposit_contract/Cargo.toml, common/deposit_contract/build.rs
NA
Addresses an item by ToB. Verifies the deposit contract ABI/bytecode during a `build.rs` script.
NA
=> Add checksum verification for deposit contract

Cargo.lock, Dockerfile, lighthouse/Cargo.toml, lighthouse/src/main.rs
N/A
Modifies the Lighthouse binary --version to include the latest commit info.
For e.g. 
```sh
$ lighthouse --version
Lighthouse 0.1.2-265234b85(modified)
```
The "modified" indicates that the binary is compiled with further modifications on top of the commit.
I think this is minimal and would be useful for debugging issues. Can include more info if needed :)
In case the .git folder or git is not available, version is just the crate_version (`Lighthouse 0.1.2`). 
This will happen in the docker build as well since the resulting docker image contains the commit source as metadata anyway. 
If we want the commit info in the docker image version as well, would have to change the Dockerfile to "git clone" the repo instead of COPY. Not sure if we want that.
=> Add latest commit info to git version

beacon_node/eth2_libp2p/src/discovery/mod.rs
N/A
In some cases, validators were missing attestations on the Altona testnet. This could be one of the reasons why we are missing attestations.
On receiving an attestation duty, the beacon node should ensure that it has some minimum sufficient peers. If not it should make a discovery query for peers in that subnet.
Before making the discovery subnet query, we check if the query has expired and retain only ones that are still valid here:
https://github.com/sigp/lighthouse/blob/559b7c8faa839d218d464479861010a21e38465e/beacon_node/eth2_libp2p/src/discovery/mod.rs#L420
This PR fixes a bug in the query expiry calculation because of which the discovery queries would not have been made even if we didn't have sufficient peers in that subnet.
Note: Most of the times, we end up not having to make …
=> Fix query expiry computation

validator_client/src/duties_service.rs
N/A
This PR fixes an edge case I hit while running altona where the VC didn't resubscribe after a change in duties due to a chain reorg.
After the duties change, we should have ideally received `InsertOutcome::Replaced {should_resubscribe: true}` and subscribed to the updated duty here:
https://github.com/sigp/lighthouse/blob/e8d5d37bc15f0e5a19248f564fba687f2d1f126f/validator_client/src/duties_service.rs#L645
but we received `should_resubscribe` as `false`.
=> Fix condition for resubscription

beacon_node/eth2_libp2p/src/behaviour/mod.rs
N/A
Removes outdated comments as the gossipsub LRU cache has been removed in https://github.com/sigp/lighthouse/pull/1324.
=> Small fix: Remove outdated comments

Cargo.lock, beacon_node/eth2_libp2p/Cargo.toml, beacon_node/eth2_libp2p/src/behaviour/mod.rs, beacon_node/eth2_libp2p/src/discovery/mod.rs, beacon_node/eth2_libp2p/src/peer_manager/mod.rs, lighthouse/environment/Cargo.toml
Updates the discovery protocol to the latest version. 
Along with this, updates to the queuing metrics and logs.
The discovery update provides fixes that prevents a thread deadlock. This results as a CPU usage load in lighthouse with no connected peers and effectively a stalled client.
=> Discovery update

beacon_node/network/src/attestation_service/mod.rs, beacon_node/network/src/metrics.rs, beacon_node/network/src/router/mod.rs, beacon_node/network/src/service.rs
Ideally, on receiving an unaggregated attestation, we should forward the attestation to gossip if the attestation verification passes. Not doing so might lead to missed attestation in the following scenario:
- We are scheduled to attest on some slot `X` of an epoch
- We are connected to `n` peers on that subnet. All `n` are Lighthouse peers who are **not** aggregators for slot `X`. Hence, when they receive our attestation, they don't forward it to their gossip peers who might be aggregators:
https://github.com/sigp/lighthouse/blob/fc5e6cbbb0f5c7ef139aeb76662ff21d995eeff5/beacon_node/network/src/service.rs#L349-L352
Hence, our attestation doesn't reach an aggregator and we miss the attestation for the slot.
Adds a `bool` field to the `RouterMessage::PubsubMessage` variant which indicates …
=> Fix attestation propagation

Cargo.lock, beacon_node/eth2_libp2p/src/rpc/protocol.rs
N/A
For rpc requests, the spec requires that 
>The requester MUST close the write side of the stream once it finishes writing the request message.
which we weren't doing. Tested this fix on altona and onyx and it is working fine. Able to peer with Teku peers as well.
=> Close outbound rpc stream after sending

Cargo.lock, beacon_node/eth2_libp2p/Cargo.toml, beacon_node/eth2_libp2p/src/config.rs, lighthouse/environment/Cargo.toml
There was a bug in discv5 which could lead to a panic. This appeared to be exasperated by performing re-requests of discovery packets. 
This PR updates discv5 to a version which addresses the panic and removes retries from the discovery protocol. 
It also updates the minimum number of peers before our local ENR gets updated to 10, to prevent the chance of non-contactable addresses being added to the DHT.
=> Discv5 update

Cargo.lock, beacon_node/eth2_libp2p/Cargo.toml, beacon_node/eth2_libp2p/src/behaviour/mod.rs, beacon_node/eth2_libp2p/src/config.rs, beacon_node/eth2_libp2p/src/peer_manager/mod.rs, beacon_node/eth2_libp2p/src/peer_manager/peer_info.rs, beacon_node/eth2_libp2p/src/peer_manager/peerdb.rs, beacon_node/src/cli.rs, beacon_node/src/config.rs
#1374 
We replace the `max_peers` cli argument by `target_peers`. Furthermore a `PEER_EXCESS_FACTOR` gets introduced that is a relative excess limit for the number of peers above `target_peers`. If more peers than target_peers are connected we disconnect the ones with the worst scores in regular intervals (`PeerManager` heartbeat).
=> Replace max_peers cli argument by target_peers and use excess peers

beacon_node/beacon_chain/src/attestation_verification.rs, beacon_node/beacon_chain/src/block_verification.rs
NA
In #1386, @AgeManning asks for my input on how to downvote peers based on block/attestation errors.
In addition to the [existing comments](https://github.com/sigp/lighthouse/blob/3c4daec9af993f3a9416c6b3141f2c9689c71418/beacon_node/network/src/router/processor.rs#L604-L793), in this PR I have added some more comments to the block/attestation error enums.
I hope this helps! Let me know if you have any questions
=> Add info about peer scoring to block/attestation errors

Cargo.lock, beacon_node/eth2_libp2p/src/peer_manager/mod.rs, beacon_node/network/src/sync/block_processor.rs, beacon_node/network/src/sync/range_sync/chain.rs
N/A
Downgrade the WARN logs from the RPC and sync (which are primarily for debugging) which pollute a normal terminal with warnings.
=> Downgrade sync and rpc warn logs

Cargo.lock, beacon_node/eth2_libp2p/src/peer_manager/score.rs
Banned peer's scores would decay rapidly once the banning timeout expired. 
Update the decay logic for banned peers to start once the banned peer timeout expires.
=> Update score decay behaviour

crypto/bls/Cargo.toml, crypto/bls/src/generic_aggregate_public_key.rs, crypto/bls/src/impls/blst.rs, crypto/bls/src/impls/fake_crypto.rs, crypto/bls/src/impls/milagro.rs
n/a
Subgroup checks are added for `blst` and updated in `milagro_bls`.
Subgroup checks will now be done:
- during deserialisation for `PublicKeys`
- during verification for `Signatures`/`AggregateSignatures`
We can no longer safely aggregate Signatures that have not been verified. The only place `Signature` aggregation currently occurs is during `Attestation` aggregation which will only be done if the signature is verified.
Currently we are pointing to our own fork of blst again to expose the subgroup checking function. We should update back to supranational/blst after this PR is merged https://github.com/supranational/blst/pull/35.
=> Update blst and milagro_bls subgroup checking
